### ISSUE TITLE
ETL_THROW_EXCEPTIONS + ETL_LOG_ERRORS failes to compile

### ISSUE THREAD

**Issue by dominicpoeschko** [ETLCPP/etl#132]
[error_handler.h#L127](https://github.com/ETLCPP/etl/blob/master/include/etl/error_handler.h#L127)
`#define ETL_ASSERT(b, e) {if (!(b)) {etl::error_handler::error((e)); throw((e);)}}`
[](url)
the semicolon is in the wrong place

should be
`#define ETL_ASSERT(b, e) {if (!(b)) {etl::error_handler::error((e)); throw((e));}}`
i guess

**Comment by jwellbelove** [comment]
Thanks, I'll that asap.

**Comment by jwellbelove** [comment]
Fixed
