### ISSUE TITLE
Comparison operators not in etl namespace

### ISSUE THREAD

**Issue by jpan127** [ETLCPP/etl#133]
Hi, I recently started using these containers `etl::{ set , unordered_set , map , unordered_map }` in larger structures / containers.  However, these outer containers require the comparison operators of these etl containers.

The compiler could not find these operators for `etl::{ set , map}`, I believe because the operators are in the global namespace not the `etl` namespace so ADL fails.

Maybe other containers are namespaced like this too, I did not check.  Please let me know if you agree, I am happy to make a PR!

**Comment by jwellbelove** [comment]
Yes, I put all of the non-member operators in the global namespace (some time ago). I had a read up on ADL (to be honest, I hadn't really looked too hard at ADL rules up until now) and I can see that I should have put them in the ETL namespace.

**Comment by jpan127** [comment]
Cool! So would you like me to assist in making the change?

**Comment by jwellbelove** [comment]
That would be a great help. It should be a fairly simple cut & paste job. We just have to keep track of what's been converted. We should keep an updated list of converted classes, either here or on Slack, while the work is in progress.

**Comment by jwellbelove** [comment]
Can you make sure you make the changes in a 'feature' or 'hotfix' branch, rather than 'master', thanks.

**Comment by jpan127** [comment]
Made a PR in a feature branch, please take a look whenever!

**Comment by jwellbelove** [comment]
I may not be able to look until Moday, as I'm off to a party in on a farm in Portesham, Dorset this weekend.

**Comment by jpan127** [comment]
Have fun!!
