### ISSUE TITLE
Virtual destructor in etl::random pulls heap managment functions on gcc

### ISSUE THREAD

**Issue by peku33** [ETLCPP/etl#134]
etl::random defines virtual destructor by default, and there is no option to disable it.
when such object is used, its vtable references operator delete related stuff, that pulls lots of bloat into binary.
Also all virtual methods are pulled in, no matter if they are used or not.
range() pulls in integer division which is unavailable on some platforms (like cortex-m0)

Example:
```
#include <etl/random.h>

#include <stm32f0xx.h>

extern "C" auto SystemInit() -> void {}
extern "C" auto _init() -> void {}

int main()
{
    etl::random_xorshift r(0);
    r();

    while(true);
}
```

Pulls in:
- _free_r (by operator delete)
- impure_data (no idea)
- __sf_fake_stdout (by free)
- udivsi3 (by range)
- (...)
Total program size: 2923B

If the destructor is not virtual:
Total program size: 1623B, less bloat functions

If there is no base class at all, size goes below 1KB

Gcc flags: flto, gc-sections, Os/O2/Og, etc.

It would be nice to have ability to disable virtual base class or at least the virtual destructor.

Thanks!

**Comment by jwellbelove** [comment]
Pushed 14.27.0
ETL's random functions are now only polymorphic if ETL_POLYMORPHIC_RANDOM is defined.

**Comment by peku33** [comment]
Thank you!
