### ISSUE TITLE
Clang-Support

### ISSUE THREAD

**Issue by dthun** [ETLCPP/etl#137]
Hi, is it possible to add support for Clang? Currently when setting up the project with cmake and clang the following error occurs:

CMake Error at external/etl/CMakeLists.txt:43 (message):
Can't generate default profile for compiler: Clang

An easy way to fix this would be to also use the PROFILE_GCC_GENERIC for clang by changing line 27 in the CMakeLists.txt file to
`if ((CMAKE_CXX_COMPILER_ID MATCHES "GNU") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))`

**Comment by jwellbelove** [comment]
Either that or create a PROFILE_CLANG_GENERIC (plus clang_generic.h profile) and add that as a new line in the make file.
If you want to make the changes then I'll accept a pull request.
