### ISSUE TITLE
Upload etl to conan-center

### ISSUE THREAD

**Issue by peter-moran** [ETLCPP/etl#143]
Conan is an open source, cross platform C++ package manager. The main repository of conan packages is `conan-center`, and I would love to see etl up there.

To get on `conan-center`, all that is needed is to:
1. [Upload a package to bintray](https://docs.conan.io/en/latest/uploading_packages/bintray/uploading_bintray.html#uploading-to-bintray)
2. The open-source package author [needs to request to be put on `conan-center`](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#contributing-packages-to-conan-center)

**Comment by peter-moran** [comment]
#144 and #142 would help automate this process

**Comment by jwellbelove** [comment]
Thanks, I'll look into it. It's the last day of my contract tomorrow, so I'll shall have some time to catch up with a few ETL issues.

**Comment by peter-moran** [comment]
It looks like this process update just days after I added this ticket. Now you can get on conan through a pull request: https://blog.conan.io/2019/09/04/A-new-binary-building-service-for-Conan-center-packages.html
