### ISSUE TITLE
C++17 not supported?

### ISSUE THREAD

**Issue by jtsdana** [ETLCPP/etl#149]
Hello I was looking through the docs, and stumbled over 
"This is defined as 1 if the compiler supports C++17.Otherwise 0. The library does not currently support C++17"

Does this mean that C++17 cannot compile etl?
Or does it mean that etl does not comply with the C++17 standards with its respective containers?

**Comment by jwellbelove** [comment]
The page is probably a bit missleading. What it really means is that the ETL does not use any C++17 specific features.
