### ISSUE TITLE
"etl/string_view.h" with Keil 5 (no stl)

### ISSUE THREAD

**Issue by rolan-reznik** [ETLCPP/etl#168]
Hello,
I am using etl with Keil 5 compiler.
When .cpp file have `"etl/string_view.h"` included compilation fails, because compiler do not see an `assert` symbol. As far as I understand this error is produced by `"etl/memory.h"` header which is included by `"etl/string_view.h"` header.
`assert` macro is used by `etl::unique_ptr::reset()` method.

If it will be convenient and it is proper way to solve the issue I can add an `"assert.h"` include into `"etl/memory.h"` and make a pull request.

**Comment by jwellbelove** [comment]
Yes, do a pull request, thanks.
