### ISSUE TITLE
Feature request: Backport of std::span from C++20

### ISSUE THREAD

**Issue by peter-moran** [ETLCPP/etl#177]
I would love to see a backport of `std::span` from C++20. It is really well suited for embedded development. https://en.cppreference.com/w/cpp/container/span

**Comment by jwellbelove** [comment]
It wouldn't be too hard to create, as it's basically very similar to the older style std/etl::array_view

**Comment by jwellbelove** [comment]
https://www.etlcpp.com/array_view.html
