### ISSUE TITLE
 Feature request: move semantics for unordered_set and unordered_map

### ISSUE THREAD

**Issue by GValiente** [ETLCPP/etl#178]
It would be nice being able to move elements to these containers.

**Comment by jwellbelove** [comment]
Adding move semantics to all of the containers is on my plan of action.

**Comment by jwellbelove** [comment]
This should be supported in the latest releases

**Comment by ncedusik-commits** [comment]
What is the reason for saving the elements of the old object when moving? This behavior was set intentionally and the testing stated "Move does not clear the source". I didn't find any explanation in the comment.

Commit: a108addf84f5c1727cae98d4b3be19507e766578
