### ISSUE TITLE
type_def.h: 'explicit' keyword on user-defined conversions is a C++11 feature.

### ISSUE THREAD

**Issue by clegg89** [ETLCPP/etl#18]
A [recent change to type_def.h](https://github.com/ETLCPP/etl/commit/6dcd00a0a7da3a029f3653a3890b182e624a26ce) made the user-defined conversion of tye_def objects explicit. While I agree with this principle, and would love to have it persist, explicit user-defined conversions are a feature of C++11, and my C++03 compiler is complaining.

Would it be possible to revert this change to remain compatible with C++03?

Another option I've seen used before is using the preprocessor to add C++11 features when compilers support them:
```
#if defined(__cplusplus) && __cplusplus >= 201103L
  #define EXPLICIT_CONVERSION explicit
#else
  #define EXPLICIT_CONVERSION
#endif
//...
EXPLICIT_CONVERSION operator TValue() const
```

**Comment by jwellbelove** [comment]
Hi,
Thanks for pointing that out. I'll revert the change.

As for to add features when the compiler support them, that's exactly what I've been considering that as well.
I've been doing some performance enhancements on the containers recently and could see that there would be advantages to allowing 'emplace' variants on compilers that supported them.
