### ISSUE TITLE
ETL_NODISCARD produces warning on MinGW 5.3.0

### ISSUE THREAD

**Issue by thetraumer** [ETLCPP/etl#181]
The [[nodiscard]] attribute is supported since C++17 (source: https://en.cppreference.com/w/cpp/language/attributes/nodiscard), but in ETL it's guarded using ETL_CPP11_SUPPORTED macro, which causes warning: 'nodiscard' attribute directive ignored on MinGW 5.3.0 when using cpp11.h profile.
Please only define [[nodiscard]] attribute when ETL_CPP17_SUPPORTED is set to true
Thanks in advance!

**Comment by jwellbelove** [comment]
Fixed 15.4.1
