### ISSUE TITLE
hash function for enum

### ISSUE THREAD

**Issue by firefly1250** [ETLCPP/etl#227]
I'd like to use unordered_map in which key is enum.
I can use it by defining hash function by myself, but it is inconvinient.
Could you add definition of hash function for enum like std?

**Comment by jwellbelove** [comment]
I looked at this a while ago, but came up against the need to implement a cross platform ETL version of `std::is_enum`. Implementing `etl::is_enum` requires several other type traits to be defined, all of which can be tricky to implement without help from the compiler. I may be able to put together a solution that will work for compilers that support the `__is_enum(T)` intrinsic.

**Comment by jwellbelove** [comment]
It can be tricky trying to track down which _version_ of each compiler started to define __is_enum(T).

**Comment by jwellbelove** [comment]
https://www.etlcpp.com/bitset.html
