### ISSUE TITLE
compile error on cpp03 profile with gcc

### ISSUE THREAD

**Issue by yiqianli** [ETLCPP/etl#228]
There are a couple of compile errors with cpp03 profile on the following:

1. bool_constant is not defined
https://github.com/ETLCPP/etl/blob/16fec7f49149c2894443b09c28137903d73312fe/include/etl/type_traits.h#L110

2. template parameter T is shadowed
https://github.com/ETLCPP/etl/blob/16fec7f49149c2894443b09c28137903d73312fe/include/etl/pool.h#L664

I worked around it quickly but only for cpp 03. You may have a much better view for a fix. Thanks!

**Comment by jwellbelove** [comment]
Thanks, I'll look at that now.

**Comment by jwellbelove** [comment]
Fixed 18.2.3
