### ISSUE TITLE
Feature request: bitfield::to_ulong conversion

### ISSUE THREAD

**Issue by positron96** [ETLCPP/etl#236]
Hi. 
Would it be possible to implement bitfield::to_ulong function for places where bitfield needs to be e.g. passed as bytes to other devices. As I understand, there is a corresponding function in STL.

**Comment by jwellbelove** [comment]
`etl::bitset` does not have a `to_ulong()` but it does have a more useful `value<T>()` template function.

The equivalent of `to_ulong()` would be `value<unsigned long>()`

**Comment by positron96** [comment]
Oh, thank you very much then, problem solved!

**Comment by positron96** [comment]
Also, somewhat related: can I set multiple bits at once?

**Comment by jwellbelove** [comment]
The only way to do that is to &|^ with another bitset.

**Comment by positron96** [comment]
Again, thank you! For the moment, I'm recreating a bitset from a modified uint32_t.
