### ISSUE TITLE
FSM not a message consumer

### ISSUE THREAD

**Issue by pkooiman** [ETLCPP/etl#271]
Trying to send messages to an fsm attached to a message_bus, after some head scratching I figured out that fsm returns false in is_consumer().

Is there a reason fsm should not be a message consumer, or is it safe to override is_consumer() and return true in my fsm? It seems to be working fine but I'm slightly worried I am missing something ;-)

**Comment by jwellbelove** [comment]
Yes, you are correct, `etl::fsm` should be a message consumer.

**Comment by jwellbelove** [comment]
Fixed in 18.15.4
