### ISSUE TITLE
Feature request: Simple/efficient dependency injection framework

### ISSUE THREAD

**Issue by shreyasbharath** [ETLCPP/etl#272]
Since ETL contains an enormous bunch of utilities/frameworks (FSM, message buses to name a few), one missing framework IMHO is a really simple, deterministic (static memory) dependency injection framework.

There are several out there - [Fruit](https://github.com/google/fruit), [kangaru](https://github.com/gracicot/kangaru), [Hypodermic](https://github.com/ybainier/Hypodermic), [Boost.DI](https://github.com/boost-ext/di) but I don't think they are necessarily suited for embedded/constrained environments.

Thoughts?

**Comment by jwellbelove** [comment]
Thanks, I'll take a look at those.

**Comment by jwellbelove** [comment]
Moved to 'For future consideration'
