### ISSUE TITLE
Arduino ARM GCC needs <climits> in integral_limits.h to compile

### ISSUE THREAD

**Issue by kaofishy** [ETLCPP/etl#28]
When compiling the BlinkList example using the ARM GCC version from Arduino (provided by the SAMD cores) the compiler complains about undefined LLONG_MAX. Adding <climits> to integral_limits.h resolves the issue.

**Comment by jwellbelove** [comment]
Thanks, I’ll update the code.

Sent from Mail for Windows 10

From: kaofishy
Sent: 05 May 2017 18:06
To: ETLCPP/etl
Cc: Subscribed
Subject: [ETLCPP/etl] Arduino ARM GCC needs <climits> in integral_limits.h tocompile (#28)

When compiling the BlinkList example using the ARM GCC version from Arduino (provided by the SAMD cores) the compiler complains about undefined LLONG_MAX. Adding to integral_limits.h resolves the issue.
