### ISSUE TITLE
etl::circular_buffer?

### ISSUE THREAD

**Issue by shreyasbharath** [ETLCPP/etl#283]
Hello again,

I was looking around in the documentation and I couldn't find a circular buffer implementation in ETL.

You could wrap `etl::queue` to create one, but I am not sure that'd be the most efficient implementation.

Thoughts?

**Comment by jwellbelove** [comment]
Funny enough, I was looking at adding one just yesterday.

**Comment by shreyasbharath** [comment]
Awesome!

**Comment by shreyasbharath** [comment]
@jwellbelove On top of creating a fixed size circular buffer, we should also look at adding a circular buffer `span` or `view` like so:
https://github.com/martinmoene/ring-span-lite

The proposal to add it to the C++ standard
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0059r3.pdf

**Comment by jwellbelove** [comment]
That is also an interesting feature to add.

**Comment by shreyasbharath** [comment]
Thanks for adding this @jwellbelove
