### ISSUE TITLE
CMake with MinGW on Windows. Linking tests executable ends with no library found from UnitTest++

### ISSUE THREAD

**Issue by adamkulpa** [ETLCPP/etl#300]
Hello,

I am trying to build unit tests on Windows using CMake and MinGW.

After a successful compilation of all files, building ends with a failure:

`make[2]: *** No rule to make target 'test/unittest++/install/lib/UnitTest++.lib', needed by 'test/etl_tests.exe'.  Stop.`

I think the problem is in the file:
[https://github.com/ETLCPP/etl/blob/master/test/cmake/unit-test_external_project.cmake](https://github.com/ETLCPP/etl/blob/master/test/cmake/unit-test_external_project.cmake)

In a platform detection condition.
Lines:
`if (WIN32)
set(UTPP_LIB_NAME "UnitTest++.lib")
else()
set(UTPP_LIB_NAME "libUnitTest++.a")
endif()`
Link to line:
[unit-test_external_project.cmake:15](https://github.com/ETLCPP/etl/blob/4aed78e32ceb4a729465180883dd8724b4ed90e5/test/cmake/unit-test_external_project.cmake#L15)

The problem is that the CMake with MinGW also have the WIN32 flag set to true.
This will result in an incorrect library name being selected.

My suggestion is to replace WIN32 with MSVC.
`if (MSVC)
set(UTPP_LIB_NAME "UnitTest++.lib")
else()
set(UTPP_LIB_NAME "libUnitTest++.a")
endif()`

This solution solves the problem with MinGW setup, but I do not know if it will work properly for Visual Studio, because I do not have an instance of this environment.
Is there anyone who can check the build for Visual Studio?

**Comment by jwellbelove** [comment]
Thanks for suggestion. It may also be the cause of why the CMake project fails with a similar error when I try to compile with QtCreator.
