### ISSUE TITLE
callback service and interrupts (question - not issue)

### ISSUE THREAD

**Issue by lfenster** [ETLCPP/etl#301]
Curious if there is a way to use the callback service to detect the originator of an interrupt.  Let's say I have three buttons on a board and need to know which button was pressed.  Im thinking of creating a controller which keeps track of the buttons but not sure if there is a way to get the originator of the interrupt without creating a separate callback function for each button.  Looking at the callback service example, I think it might be similar to the UART example but each of those has its own vector id associated with it.  If i call addInterrupt for a CHANGE to each button and associate it with its pin, how can I get the callback to know which button was actually pressed?

Any help would be greatly appreciated.
Thanks

**Comment by jwellbelove** [comment]
The callback interface is designed decouple a set of interrupt vectors from their handlers. It is in one of these handlers that you would read the buttons to see which one was pressed.

If you created three dummy interrupt vector ids, you could read the buttons _before_ the callback function is called and use the dummy id as the template or function parameter, but that would be mixing the real interrupt vector ids with fake ones, which would end up being confusing. It would be better to use the callback as a proxy to distribute control to the three button handlers.

IO Interrupt -> IO Interrupt handler -> IO Callback{Read buttons} -> Button handler X, Y or Z
