### ISSUE TITLE
CR: Make constexpr format_spec possible

### ISSUE THREAD

**Issue by bku-sue** [ETLCPP/etl#307]
Currently there's no possibility to define a custom constant basic_format_spec.
1. There's only a parameterless constructor.
2. The constructor isn't constexpr, even though there's nothing keeping it from being so.
3. All the internal member variables are private.

To make this possible, 2. must be changed, and at least either 1. or 3. must also be changed, so a custom format_spec can either be created through parametric constructor, or by subclassing.

**Comment by jwellbelove** [comment]
Updated 19.2.0
