### ISSUE TITLE
Using stddef.h in nullptr.h also applies to plain AVR

### ISSUE THREAD

**Issue by jputcu** [ETLCPP/etl#309]
Using ETL for a basic Atmel AVR project I get an error about not finding "cstdef".
Replacing ARDUINO with __AVR__ in "nullptr.h" fixes the issue and seems more generic.

**Comment by jwellbelove** [comment]
Updated 19.2.0

**Comment by jputcu** [comment]
My apology, the correct define should be `__AVR__`, markdown saw the underscores as formatting.
Would it be safe to just replace ARDUINO with the other define? I think it only applies to GCC not providing any C++ headers.

**Comment by jwellbelove** [comment]
OK, I'll have to re-do the push.
