### ISSUE TITLE
Use the git_version_from_git_tag() function in conanfile.py

### ISSUE THREAD

**Issue by jputcu** [ETLCPP/etl#311]
The conanfile.py has a hardcoded version but in the beginning of the file a git_version_from_git_tag() is defined.
When replacing the hardcoded version with a call to the function we get a nice version when `conan create .`.
~~~~
version = get_version_from_git_tag()
~~~~

**Comment by jwellbelove** [comment]
Fixed in 19.2.1
One day I may find the time to figure out how to get this on Conan centre
