### ISSUE TITLE
Cannot instantiate container with object (etl::set, maybe more)

### ISSUE THREAD

**Issue by NeimadG** [ETLCPP/etl#33]
Using "key_value_parameter_t&"  make it impossible to use object in etl::set. As key_value_parameter_t is derived from etl::parameter_type, when a reference is required (with an object), it is automatically used. Removing "&" solves the problem.
I did it in etl::set, but the problem might exist elsewhere (I am not a contributor, so I did my modifications locally)

**Comment by jwellbelove** [comment]
Thanks, You are correct that the 'const &' is unnecessary for non-fundamental key types as etl::parameter_type<T> already takes this into account.This affected all map/set types except for the 'flat' variants.I'll update the repository today (UK time).John.
