### ISSUE TITLE
etl::string fails to compile without a heap

### ISSUE THREAD

**Issue by mkalibat** [ETLCPP/etl#332]
It's observed that the only difference between failing (linker error) and not-failing builds is an instantiation of etl::string<64>. The linker failure output is:

`/opt/microchip/xc32/v2.49/bin/bin/../../lib/gcc/pic32c/6.2.1/../../../../bin/bin/pic32c-ld Error: A heap is required, but has not been specified`

Does etl::string<> have any methods that dynamically allocate?

Thanks.

**Comment by jwellbelove** [comment]
Nothing in the ETL should be allocating from the heap, but I'll investigate anyway.

**Comment by mkalibat** [comment]
Thanks!

Note that this is only observed in the debug build (with `DEBUG` macro defined). I see this enables the ETL_DEBUG macro. Are there some print functions or such enabled in debug mode?

**Comment by jwellbelove** [comment]
What ETL error handling option macros have you set?

**Comment by jwellbelove** [comment]
Could `assert()` be using heap memory?
