### ISSUE TITLE
With release 19.5.1 C++98/03 mode stopped working

### ISSUE THREAD

**Issue by bolry** [ETLCPP/etl#343]
Example simple main.cpp
```c++
#include <etl/string.h>
int main() {}
```
one defined etl_profile.h with the following content: #include <etl/profiles/cpp03.h>

`g++ -I. -Ietl-src/include -std=gnu++98 main.cpp` 
Gives
.../include/etl/string_view.h:312:51: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
.../include/etl/string.h:357:90: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11

With clang++ I get a warning instead:
string_view.h:311:44: warning default template arguments for a function template are a C++11 extension [-Wc++11-extensions]
template <typename TIterator, typename = typename etl::enable_if<!etl::is_integral<TIterator>::value, void>::type>

With release 19.5.0 this compiles and links OK for both compilers.

**Comment by jwellbelove** [comment]
OK, I will check that today.

**Comment by jwellbelove** [comment]
Fixed in 20.6.0
