### ISSUE TITLE
etl::array is not constexpr

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#344]
I have had to fall back to using the `std::array` due to `etl::array` not being `constexpr`.  As far as I can tell, most, if not all, of the `etl::array` functionality should be able to get appended with `ETL_CONSTEXPR`.

**Comment by jwellbelove** [comment]
Thanks, I'll look into implementing that.

**Comment by jwellbelove** [comment]
Fixed in 20.6.0

**Comment by jovere** [comment]
This is broken again in 20.6.2.

**Comment by jovere** [comment]
Nevermind, it looks like I'm just confused.  It was removed on some of the functions, like `iterator begin()` and didn't understand why.  However, I just realized it's due to the array not being const in the first place and it doesn't matter.  Sorry for the distraction.
