### ISSUE TITLE
Compiler issue with `pool.h`

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#345]
I'm having a build issue with pool.h in IAR Embedded Workbench.  I'm getting an error with the following line:
https://github.com/ETLCPP/etl/blob/430e385e4e00892024d5a1e2f261388e6322af04/include/etl/pool.h#L172

I don't understand what the `base_t::template` does, but if I remove the `::template` and just change it to `base_t::destroy()` it compiles without error.  I noticed that the `release` function just above has the same kind of change, apparently done during an update to work with LLVM compilers.

See this commit: https://github.com/ETLCPP/etl/commit/0b2bf0e47cae4786547a8e4562a2639aba3da035#diff-cd80218359c70508fe52202d302a15367e5d0558053c8ac9a05ff52e75cfc4fb

My questions are this: what does the `base_t::template` do, and can it be changed the same way in `destroy()` as it was in `release()` without any issue?

Thanks,
Jeremy Overesch

**Comment by jwellbelove** [comment]
Fixed in 20.6.0
