### ISSUE TITLE
In C++98/03 mode you get: default template arguments may not be used in function templates without ‘-std=c++11’

### ISSUE THREAD

**Issue by bolry** [ETLCPP/etl#349]
In release v20.6.0 you get for the following headers:
deque.h, forward_list.h, intrusive_forward_list.h, intrusive_list.h, list.h, map.h, multimap.h, multiset.h, set.h, span.h, and finally vector.h. This also applies to the family of crcNN_xyz.h headers too.

To reproduce just include any one of the headers and compile in C++98/03 mode.

E.g. `/usr/bin/g++-10  -I. -isystem etl-src/include -std=gnu++98 -c vector.h.t.cpp`

I have a `etl_profile.h` with the content: `#include <etl/profiles/cpp03.h>`.

**Comment by jwellbelove** [comment]
ETL_STRING_FILE_ID
