### ISSUE TITLE
Can't compile format_spec in C++98/03 mode

### ISSUE THREAD

**Issue by bolry** [ETLCPP/etl#350]
Compiling `etl/format_spec.h` i get: `basic_format_spec.h:163:60: error: in C++98 ‘etl::bin’ must be initialized by constructor, not by ‘{...}’`

Compiling with `g++  -I. -isystem etl-src/include -std=gnu++98 -c format_spec.h.t.cpp`
With a `etl_profile.h` with the content `#include <etl/profiles/cpp03.h>`.

**Comment by jwellbelove** [comment]
Fixed in 20.6.2
