### ISSUE TITLE
Add support for moveable only paramters to delegates

### ISSUE THREAD

**Issue by Chiraffollo** [ETLCPP/etl#357]
Currently, it is not possible to forward parameters that can't be copied but only moved as parameter to a delegate call.
Therefore, I suggest to use std::forward to enable this feature. #356

**Comment by finger42** [comment]
Any plans to bring this mainline?

**Comment by jwellbelove** [comment]
Yes, possibly today.

**Comment by jwellbelove** [comment]
Pushed to 20.7.0
