### ISSUE TITLE
circular_buffer operator [] takes integer rather than size_type

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#363]
The following two functions are taking an `int` rather than a `size_type`.  This results in a narrowing conversion from an unsigned value to a signed value.

https://github.com/ETLCPP/etl/blob/026dfb838861eb6c26333a81ce622d130c70546a/include/etl/circular_buffer.h#L815
https://github.com/ETLCPP/etl/blob/026dfb838861eb6c26333a81ce622d130c70546a/include/etl/circular_buffer.h#L824

**Comment by jwellbelove** [comment]
Fixed v20.9.0
