### ISSUE TITLE
Question: robin hood hashing?

### ISSUE THREAD

**Issue by jwdevel** [ETLCPP/etl#364]
I've just started playing with this library, and I'm especially interested in hash-based containers.

From reading around, I hear that "robin hood hashing" (exemplified by the [robin-map](https://github.com/Tessil/robin-map) lib and described well by this [blog post](https://www.sebastiansylvan.com/post/robin-hood-hashing-should-be-your-default-hash-table-implementation/)) is good for high-load hash tables. I would imagine that is a good fit for ETL users, given the fixed-size storage.

I'm just curious if you have looked at it, and perhaps decided against it for some reason or other?
From looking quickly, ETL seems to use a more traditional linked-list based chaining approach.

**Comment by jwellbelove** [comment]
I don't think I've looked at "robin hood hashing" before.
I'll check it out.
