### ISSUE TITLE
Add install option

### ISSUE THREAD

**Issue by aboseley** [ETLCPP/etl#367]
The project should include an install target, along with the cmake configuration info

**Comment by jwellbelove** [comment]
Can you expand on what you mean by "an install target"?

**Comment by aboseley** [comment]
Pretty much, we should be able to build, test, then install the etl package.  I understand its header only but the workflow should still be the same.  Target as in makefile target, or cmake target,  I'll send thru a merge request in next few days to show what I mean.

**Comment by jwellbelove** [comment]
In 20.9.1
