### ISSUE TITLE
etl::vector assumes STL std::distance and won't compile without STL

### ISSUE THREAD

**Issue by adfernandes** [ETLCPP/etl#370]
Segger Embedded Studio 5.42a, using the `gcc-10-2020-q4-major` toolchain.

I have a file that uses `etl::vector`, but [here](https://github.com/ETLCPP/etl/blob/20.9.0/include/etl/vector.h#L1750) and [here](https://github.com/ETLCPP/etl/blob/20.9.0/include/etl/vector.h#L1764) the assumption is to use `std::distance`.

Unfortunately, `std::distance` is not available without the STL.

The ETL `vector.h` **does** include the ETL `iterator.h`, but that defines `etl::distance`, not `std::distance`.

**Comment by jwellbelove** [comment]
Fixed 20.9.1
