### ISSUE TITLE
Feature Request etl::message virtual inheritance

### ISSUE THREAD

**Issue by fermentedfly** [ETLCPP/etl#384]
Hi,

I'm currently using some message objects which inherit from etl::message and my own interface.
I'd like my interface to inherit from etl::imessage so i do not need to store references to etl::imessage and my own interface separately.
```c++

class IMyInterface : public etl::imessage
{
virtual void foo() = 0;
};

class MyMessage : public etl::message<...>, public IMyInterface
{
};
``` 
Currently, this does not work since it will result in a diamond like inheritance.
Afaik, virtual inheritance would solve the issue, i.e.

```c++
  template <etl::message_id_t ID_>
  class message : public virtual imessage
```
Would it be possible to change etl::message to use virtual inheritance?

**Comment by jwellbelove** [comment]
Would `IMyInterface` be the same for all messages?
(Sorry for the delay in replying)

**Comment by fermentedfly** [comment]
No worries, Yes `IMyInterface` is the same for all messages (for a given event bus, there are other buses with with messages not inheriting from `IMyInterface`)

**Comment by jwellbelove** [comment]
One option is to add a macro to control this so that it is optional, something like...
`ETL_MESSAGE_INHERITANCE_IS_VIRTUAL`.

Another would be to allow `etl::message` to take another template parameter, which defines what `etl::message` derives from.
This would turn it from multiple inheritance to single inheritance.

**Comment by jwellbelove** [comment]
```

       etl::imessage
             |
      ________________
      |              |
etl::message<>  IMyInterface
      |              |
      ________________
             |
          MyMessage


       etl::imessage
             |
        IMyInterface
             |
       etl::message<>
             |
          MyMessage
```

**Comment by jwellbelove** [comment]
```
class IMyInterface : public etl::imessage
{
    virtual void foo() = 0;
};

class MyMessage : public etl::message<ID, IMyInterface>
{
    void foo() override;
};
```

**Comment by fermentedfly** [comment]
Thanks for the input, if you want me to i will look into it and send a PR if it works out. I guess a second template parameter which defaults to etl::imessage is neater than the using a macro

**Comment by fermentedfly** [comment]
something like
```
  template <etl::message_id_t ID_, class PARENT_ = etl::imessage>
  class message : public PARENT_
```

**Comment by jwellbelove** [comment]
Pretty much what I was looking at, except I would prefer

```
  template <etl::message_id_t ID_, typename TParent = etl::imessage>
  class message : public TParent
```
An `ETL_STATIC_ASSERT` to check that `etl::imessage` is a base of `TParent` would stop mistakes when using an incompatible type.

**Comment by jwellbelove** [comment]
`ETL_STATIC_ASSERT(etl::is_base_of<etl::imessage, TParent>::value, "TParent is not derived from etl::imessage");`

**Comment by fermentedfly** [comment]
Ok, will do.
