### ISSUE TITLE
basic_string::copy() is not const

### ISSUE THREAD

**Issue by erigusaab** [ETLCPP/etl#388]
etl::basic_string::copy() is not const, unlike the STL equivalent.
This must be because of the use of set_truncated(true), however I don't understand why the (source) string should be marked as truncated because of attempts to read too much data from it.

Is this a bug in ETL, or my misunderstanding?

**Comment by jwellbelove** [comment]
Yes, that looks incorrect, it shouldn't be setting the source string's flags.
