### ISSUE TITLE
forward_list documentation

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#398]
On the page regarding the `forward_list` documentation (https://www.etlcpp.com/forward_list.html) it states that calling `begin()` and `end()` on an empty list results in undefined behavior.  This seems very odd to me, as I would expect it to return an iterator to `nullptr`.  If it was truly undefined behavior, I would expect that this would be a problem for many algorithms. Am I missing something?

**Comment by jwellbelove** [comment]
The documentation is incorrect. `begin()` on an empty list returns `end()`.
