### ISSUE TITLE
observable::notify_observers() gives compiler error when the passed type is a reference

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#407]
There is a fairly confusing issue with the `notify_observers()` function that is not immediately obvious.  For example, I create an observer and observable with the following definition:

```C++
struct myStruct {};

typedef etl::observer<myStruct&> myObserver;

class anObservable : public etl::observable<myObserver, 1> {
 public:
  void notifySomebody() { notify_observers(data); }

  myStruct data;
};
```

When I call `notifySomebody()`, `data` is being passed by copy to the `notify_observers()` function, not reference. I came across this when I marked the copy/move constructors of `myStruct` as deleted. The immediate way to fix the issue is to call notify_observers with the following: `notify_observers<myStruct&>(data);`  However, it's not immediately apparent to the end user that this is necessary if they don't have the copy/move constructors deleted.

Changing the `notify_observers()` function so there are two versions, one taking a reference and the other an r-side reference seems to fix the issue in modern C++, but I am unsure how to fix it in C++03 and if there is a more elegant solution.

Thanks,
Jeremy

**Comment by jwellbelove** [comment]
I ideally, I suppose observable would interrogate the observer types in the template parameter list and define a `notify_observers()` for each notification type that they expect. I have no idea whether that is possible.

Onthe other hand...
The `notify_observers()` function would not need two variants as it is a template function and therefore a parameter declared as `&&` would be a 'universal reference'. What the function would then `forward` the parameter to `notification()`.

I don't think there's much that can be done for C++03, apart from the fix you used. I'll have to make a note in the documentation.
