### ISSUE TITLE
Queue's `pop_into` copies rather than moves

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#413]
In the following line of code, the `front()` function is used to copy the data into the reference before popping it off.  Unless I am mistaken, it would seem like a better way to do this would to have the move assignment operator be called, so those objects with copy disabled, but move allowed, would still be allowed in a queue.
https://github.com/ETLCPP/etl/blob/a23979d449ac6cdc3911f327ec8ee0112d254877/include/etl/queue.h#L455

**Comment by jwellbelove** [comment]
Added in 20.16.0
