### ISSUE TITLE
Successor for message bus

### ISSUE THREAD

**Issue by edvvasdal** [ETLCPP/etl#414]
Thanks for a great library.
In the implementation of message_bus there are missing support to forward unhandled message to its successor.
A suggestion could be to add this:
```
if(router.has_successor()) 
{
    etl::imessage_router& successor = router.get_successor();
    if(successor.accepts(message.get_message_id()))
    {
        successor.receive(message);
    }
}
```
To the function `void receive(etl::message_router_id_t destination_router_id, etl::imessage& message);`

**Comment by jwellbelove** [comment]
20.17.0
Added successor for all `etl::imessage_router` derived classes.
