### ISSUE TITLE
[Suggestion] Add a message buffer container (like the one in FreeRTOS)

### ISSUE THREAD

**Issue by positron96** [ETLCPP/etl#417]
Hi and thanks for awesome library!

In FreeRTOS there is a [MessageBuffer](https://www.freertos.org/RTOS-message-buffer-example.html) object that is essentially a FIFO container, where you put objects of various sizes (e.g. strings) and retrieve them later. Being FreeRTOS, it is all wrapped in mutexes and locks, which you don't need if you don't use RTOS. 
Compared to existing etl::queue and etl::circular_buffer, the objects can be of various sizes and they are stored densely. The interface is not very C++-y since you operate on pointers and sizes.

Would be nice to have such a container in ETL.

**Comment by jwellbelove** [comment]
Moved to 'For future consideration'
