### ISSUE TITLE
Constexpr Map/Multimap, etc

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#422]
Is there a reason Map and its related containers are not `constexpr`? I would like to create a constant lookup table, but it appears that it isn't possible. Is there a different way that could be done?

Thanks,
Jeremy

**Comment by jwellbelove** [comment]
Originally the containers were written for C++03, so 'constexpr' was not a thing at the time.
Making all of the ETL containers 'constexpr' is a case of "gradual work in progress".

**Comment by jwellbelove** [comment]
What type are your keys to the lookup table?

**Comment by jovere** [comment]
Right now I was planning to use just a regular int. Having it as a work in progress is entirely understandable. I wasn't sure if it was a limitation of the data type or some other issue. The stl doesn't have its definition of map as constexpr, either.

**Comment by jwellbelove** [comment]
If you were to create a `constexpr etl::array`, of key/value pairs, with the keys in order, then you can do an `etl::lower_bound` search on it.
