### ISSUE TITLE
minor static code analyzer warnings

### ISSUE THREAD

**Issue by mampfes** [ETLCPP/etl#441]
Hi John,

we are using https://scan.coverity.com/ for static code analysis and found some minor warnings:

1. Unsafe assignment operator (SELF_ASSIGN). No protection against assigning to itself:
https://github.com/ETLCPP/etl/blob/2d64b77e4a1684e6c8aa6977028eba924ec8831b/include/etl/map.h#L639
https://github.com/ETLCPP/etl/blob/2d64b77e4a1684e6c8aa6977028eba924ec8831b/include/etl/list.h#L532
https://github.com/ETLCPP/etl/blob/2d64b77e4a1684e6c8aa6977028eba924ec8831b/include/etl/multimap.h#L908
https://github.com/ETLCPP/etl/blob/2d64b77e4a1684e6c8aa6977028eba924ec8831b/include/etl/span.h#L261
https://github.com/ETLCPP/etl/blob/2d64b77e4a1684e6c8aa6977028eba924ec8831b/include/etl/intrusive_forward_list.h#L447
There are more some more occurrences in the code.

2. Parse warning (PW.PARAMETER_HIDDEN). declaration hides parameter "pbucket" (declared at line 1404)
https://github.com/ETLCPP/etl/blob/2d64b77e4a1684e6c8aa6977028eba924ec8831b/include/etl/unordered_map.h#L1424

Is this s.th. you would fix? If yes, I could prepare a PR.

**Comment by jwellbelove** [comment]
Yes, those are valid things to fix.
