### ISSUE TITLE
MSVC compiler fails on nodiscard

### ISSUE THREAD

**Issue by jputcu** [ETLCPP/etl#442]
Trying to upload embedded-template-library to conan-center the CI reports a failure when using MSVC:
https://github.com/conan-io/conan-center-index/pull/7649#issuecomment-940192714
It requires **/std:c++17** when using `nodiscard`.
I believe the compiler should normally just warn when it encounters unknown attributes, but apparently not in this case.

**Comment by jputcu** [comment]
I could, but the example should represent a user of the library, who could be using that old compiler to use ETL.
Could you use a MSVC environment variable to detect and disable the `nodiscard` attributes, e.g. https://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-a-particular-visual-studio-version?

**Comment by jputcu** [comment]
Before you make another version number, which I can repost to conan, you could also remove the conanfile.py, which will be managed in conan-center.

**Comment by jwellbelove** [comment]
OK,
