### ISSUE TITLE
etl::string_stream with non-const char* prints pointer value instead of the string

### ISSUE THREAD

**Issue by halecivo** [ETLCPP/etl#449]
Passing `const char *` into `etl::string_stream` properly prints the string:
```
const char * constant_str = "const";
ss << constant_str;
```
results in
`"const"`

Passing `char *` prints the pointer value instead:
`char str[] = {'t', 'e', 's', 't', '\0'};`
`ss << str;`
results in something like
`"12345678"`

**Workaround** is to cast `char *` to `const char*`
`ss << (const char*)str;`

Or to overload << operator also for char*:
```
etl::string_stream& operator <<(etl::string_stream& ss, char * value)
{
    ss << (const char*)value;
    return ss;
}
```

**Comment by jwellbelove** [comment]
Implemented 20.20.0
