### ISSUE TITLE
etl::begin()/etl::end() broken?

### ISSUE THREAD

**Issue by jovere** [ETLCPP/etl#456]
I recently tried to update my copy of the ETL to the latest and found that `etl::begin()` and `etl::end()` no longer exist. It appears that in commit f3bf0dc7fe8e1bf04a00d98e78cdf1a78f4d951d they were moved to `iterator.h` and disabled if the standard library is being used. The commit comment states that it's `etl::begin()` and `etl::end()` are being removed when `ETL_NO_STL` is defined, yet it appears to be doing the opposite. Is this intentional? Are the etl specific versions not to be used?

Thanks,
Jeremy

**Comment by jwellbelove** [comment]
The commit message is incorrect.
I had to disable the ETL's version when using the STL as there are libraries that use `using` directives with `std::begin` and `std::end` which cause ambiguous definitions between the ETL and STL versions. I had to do the same with `std::swap` vs `etl::swap` a long time ago when I started cloning parts of the STL.

**Comment by jwellbelove** [comment]
See issue #448

**Comment by jovere** [comment]
Ok, I'll start using `std::end` and `std::begin`.  Thanks.
