### ISSUE TITLE
callback_timer not restarted when set_period() is called

### ISSUE THREAD

**Issue by julr** [ETLCPP/etl#460]
According to the documentation, setting a new period on a callback_timer with set_period() restarts the timer. However inside the set_period function only stop() is called so the timer is halted but not restarted.
I don't know if this is intended (wrong documentation) or if this is a bug but I think either the implementation or the documentation should be changed so that is consistent.

**Comment by jwellbelove** [comment]
Thanks, I'll look at updating that.

**Comment by jwellbelove** [comment]
Documentation updated
