### ISSUE TITLE
std::string_view support

### ISSUE THREAD

**Issue by mrdimfox** [ETLCPP/etl#47]
In c++17 you can use an awesome class std::string_view. See more here: http://en.cppreference.com/w/cpp/string/basic_string_view
Can you add a support of a casting to std::string_view from etl::string and back? It will be extremely useful for embedded software purposes.

**Comment by jwellbelove** [comment]
std::string_view should be usable as-is, just like std::string.

etl::string text("Hello World");
std::string_view view(text.data(), text.size());

**Comment by mrdimfox** [comment]
Yes, sure. But it could be a string_view operator there in the etl::string class. string_view is a part of the standard lib (since C++17) now, so it can be useful to have one, IMHO. 😄

**Comment by jwellbelove** [comment]
OK, I will look into it.
