### ISSUE TITLE
Feature request: Add contains() method to etl::map and etl::set

### ISSUE THREAD

**Issue by zrno** [ETLCPP/etl#471]
A `contains()` method was added to std::set, std::map, std::multiset and std::multimap in C++20.

**Comment by jwellbelove** [comment]
I'm currently working on introducing this to all of the map/set containers.
I'm also adding support for 'transparent' comparators.
See [What are transparent comparators?](https://newbedev.com/what-are-transparent-comparators)

**Comment by jwellbelove** [comment]
Updated in 20.21.0
