### ISSUE TITLE
When ETL_NO_ATOMICS is defined the timer.h file should not define timer_semaphore_t

### ISSUE THREAD

**Issue by TunaBicim** [ETLCPP/etl#475]
If a processor that does not support atomics is used, compilation errors occur even when ETL_NO_ATOMICS is defined. 
This is true even if the software uses disable/enable interrupt calls for locking by defining ETL_CALLBACK_TIMER_USE_INTERRUPT_LOCK and the function flags.

**Comment by jwellbelove** [comment]
Updated in 20.21.0
