### ISSUE TITLE
Different ifdefs for container overflow handling 

### ISSUE THREAD

**Issue by mampfes** [ETLCPP/etl#476]
Why is there a different handling regarding overflow asserts for `push_back` and `assign` in the containers?
The assert in `push_back` is ifdef'ed with the very specific ETL_CHECK_PUSH_POP.
The assert in `assign` is ifdef'ed with the very generic ETL_DEBUG.

The problem is, that if I want to enable runtime checks for any kind of overflow error, I have to enable `ETL_CHECK_PUSH_POP` and `ETL_DEBUG`.

```c++
    void push_back(const_reference value)
    {
#if defined(ETL_CHECK_PUSH_POP)
      ETL_ASSERT(size() != CAPACITY, ETL_ERROR(vector_full));
#endif
      create_back(value);
    }
```

```c++
    template <typename TIterator>
    typename etl::enable_if<!etl::is_integral<TIterator>::value, void>::type
      assign(TIterator first, TIterator last)
    {
      ETL_STATIC_ASSERT((etl::is_same<typename etl::remove_cv<T>::type, typename etl::remove_cv<typename etl::iterator_traits<TIterator>::value_type>::type>::value), "Iterator type does not match container type");

#if defined(ETL_DEBUG)
      difference_type d = etl::distance(first, last);
      ETL_ASSERT(static_cast<size_t>(d) <= CAPACITY, ETL_ERROR(vector_full));
#endif
```
The example is taken from etl::vector.

**Comment by jwellbelove** [comment]
I made it an optional debug feature as push_back is often used in loops which could result in an unacceptable runtime overhead for debug builds.

**Comment by mampfes** [comment]
OK, so this means that this is just a debug feature and not meant to be used in release code.
