### ISSUE TITLE
push regularly to https://github.com/ETLCPP/etl-arduino ?

### ISSUE THREAD

**Issue by jerabaul29** [ETLCPP/etl#478]
It looks like https://github.com/ETLCPP/etl-arduino is a bit outdated; any reason for not pushing to it / should / could a github action workflow or similar be set up to periodically push to it? :) .

**Comment by jwellbelove** [comment]
The Arduino version of the ETL has a slightly different file layout (mandated by the Arduino platform), and doesn't include the unit tests. I already have a python script that copies the relevant code into another directory, so I should probably get into the habit of running it for every release.

**Comment by jerabaul29** [comment]
That would be amazing :) .

**Comment by jerabaul29** [comment]
Feel free to close :) . Wonder if there is a way to automate the running of the script and pushing to the arduino repository when a release is performed? :).

**Comment by jwellbelove** [comment]
It's much easier for me to just remember to go to the Arduino directory and type `python .\create_arduino_library.py`
The only issue that may occur with the Arduino version is that I don't really have the time to do any extensive testing to check for compatibility. I test with VS2019 & clang on Windows and GCC & clang on Linux (with permutations of STL/No STL C++03, using compiler 'built-ins' etc), but the Arduino platform does have the occasional 'quirk'.
