### ISSUE TITLE
FSM on_exit_state called on the new state instead of the old state

### ISSUE THREAD

**Issue by AODtorusan** [ETLCPP/etl#48]
In the Finite State Machine code, when there is a state transition, the on_exit_state function is called after the state has already changed. This means that the on_exit_state is executed for the new state instead of for the old state;

https://github.com/ETLCPP/etl/blob/88cc021c8c3c49f934172999a49392322013f259/src/fsm.h#L305-L313

I think the state update line 309 and the on_exit_state call on line 310 should be swapped.

**Comment by jwellbelove** [comment]
Thanks, fixed.
