### ISSUE TITLE
vector `test_uninitialized_resize_excess` not calling `uninitialized_resize`

### ISSUE THREAD

**Issue by gmrehbein** [ETLCPP/etl#484]
test_vector.cpp line 385 reads:

`CHECK_THROW(data.resize(NEW_SIZE), etl::vector_full);`

It should be:

`CHECK_THROW(data.uninitialized_resize(NEW_SIZE), etl::vector_full);`

**Comment by jwellbelove** [comment]
Fixed 20.22.0
