### ISSUE TITLE
Created Slack group

### ISSUE THREAD

**Issue by jwellbelove** [ETLCPP/etl#49]
I have created a Slack group to better support the ETL.
You can find it [here](https://slofile.com/slack/etlcpp)

EDIT: Updated link.

**Comment by apmorton** [comment]
>This invite link is no longer active.

According to slack: 

> For security, invite links will expire and can be used by up to 1000 people. If you need to, you can get a new link.

I suggest you list the slack team on [slofile](https://slofile.com/) - which is a directory of public slack teams, but also has a built in invite feature that won't self destruct after some period of time like slacks shared invite feature.

**Comment by jwellbelove** [comment]
Thanks. I've updated the link to take people to slofile.
