### ISSUE TITLE
Documentation: ETL_ARRAY_VIEW_IS_MUTABLE is not documented on macros.html

### ISSUE THREAD

**Issue by mbschenkel** [ETLCPP/etl#494]
The option `ETL_ARRAY_VIEW_IS_MUTABLE ` was introduced with 17.6.0 and is in use by [`array_view.h`](https://github.com/ETLCPP/etl/blob/0b5fa009843e6e7d5f827c8fb55e7fef0a6b61bf/include/etl/array_view.h) but is missing from https://www.etlcpp.com/macros.html

**Comment by jwellbelove** [comment]
Fixed
