### ISSUE TITLE
Improve language detection for Visual Studio

### ISSUE THREAD

**Issue by fazaldegui** [ETLCPP/etl#496]
Hello,
I've had a little issue with the detection of cpp support. For vs2019 is detected that it support C++17 but sometimes you can not use std=c++17 because your linking with other libraries in other standart. Moveover, in vs2019 the default is for C++14.
In that case I think is better to look the _MSVC_LANG macro that it value depends in the -std=c++xx  compilation flag.

I've made a modification for this and it work in vs2019, vs2010 and also I tried for gcc-linux. I attach the patch. Just a little modification in file "determine_compiler_language_support.h".
[determine_compiler_language_support.zip](https://github.com/ETLCPP/etl/files/7907373/determine_compiler_language_support.zip)

For any question I'm here. Thank for this great library.
Regards,
Fernando

**Comment by jwellbelove** [comment]
Thanks, I'll merge that into the code on the next release.
