### ISSUE TITLE
Algorithm `transform` uses expensive post increment operator

### ISSUE THREAD

**Issue by jputcu** [ETLCPP/etl#503]
Trying to use `etl::transform` on an ArduinoJson Array worked on PC but didn't on AVR. It appears on PC the fallback is `stl` which works with a pre-increment but the etl version uses post increment which failed to compile due to missing operator overload.
It is my understanding that the post increment operator creates a copy of the iterator (=expensive).

**Comment by jwellbelove** [comment]
The ETL uses the idiom of dereference + post-increment throughout the code.
This issue may be relevant in more than just `etl::transform`.

**Comment by jwellbelove** [comment]
20.24.0
