### ISSUE TITLE
ETL_CONSTANT vs const in binary.h

### ISSUE THREAD

**Issue by mbschenkel** [ETLCPP/etl#504]
Shouldn't `const` here in `binary.h` be replaced with `ETL_CONSTANT`? 

Here
https://github.com/ETLCPP/etl/blob/13b28387c5b45006b6f4a658d28a24c0d489e416/include/etl/binary.h#L104
and
https://github.com/ETLCPP/etl/blob/13b28387c5b45006b6f4a658d28a24c0d489e416/include/etl/binary.h#L384

At least for some older gcc this leads to
```
Output of PowerPC gcc 4.8.5 (Compiler #1)
<source>:27:85: error: redeclaration 'etl::max_value_for_nbits<NBITS>::value' differs in 'constexpr'
   const typename max_value_for_nbits<NBITS>::value_type max_value_for_nbits<NBITS>::value;  
```

from [this minimal example on godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYgAzKVpMGoZAFIATACFLV0kvrICeAZUboAwqloBXFgwkAVlJ3ABk8BkwAOT8AI0xiEAAOUgAHVAVCFwYvX38gtIysgXDImJZ4xJSHTCdsoQImYgJcvwCuYJq6gQamglLouITk%2B0bm1vyO0b6B8srkgEp7VB9iZHYOSz0I5F8sAGozPQ9kBQJ8QSPsMw0AQQIAT1TMLCp9s/QQEEyAL0wAfQI7zwf0BRxsdy2rwimH22AAKqF/h4APJRITw25ReH7NAMM6YVSpYg3W6k5hsBSpJjrfaYAi0UlmADsENu%2B32AHpOQAqPn8gWCoXCkWisXi0Wkjnczn7AAimBoDGKDH2/GI%2BwYAgAtH9iKh9lErABJeFCAB0Uv2BEwLFSRhth2OeLOwNBQKNpqEVytZ2IPic%2BxYTFU/wAbmIfAD1f8GLFCAorSy2RzpZzHs9XtanoxWLD6bQvgpg7R6Gd/j4IgR/jH4wRE8dPWarl8M7CI74AW3wVaOW2sz58XhgJF0PsO1HATme3dU%2B9Gs5kHDEci0RisTiJ12c%2BPI7CjnL9hAt1PnhAuAsnR4jh4j02hPttfsL5eWbfg6GTzG4wmb/fH8%2BLYgFuM7soczJyqBVoyvsQjPMgeBiHgChMM4AhqiQ%2BwAO4IIwhommaTqQXoh4aJas7Wra9qofuxw%2BhRfoBkCH7hnuNYkLGdYNh4Gj0WBya9qm3L9oqdIMkWJZltWlaCOxxD/FxN68Xo2CtjuJ7dnoKZztmmaiYOmQji8u6dqemCgTp86oXgS4IkiqLopi2ImZObYubRpEWeBxFslaNp2g6tEnAIrq/F2%2BFenxHIukCbYUrCLFfhxP71n%2BBHeipXwaTuiVsd%2BimNulQEgVpHJJhR3LYSQADWCggNBsr%2BdRjo3jFbrhfeUVcrKdmro5G66bmbBBiGrGmflv6FZFmXAWxbm5eNyUFR4nUzSVVhlZCEGkhwSyFhwgS8AEHBaKQqCcNe1i2O8KxrPuFh6HovAEJou1LLhTBYIkEBLNVICBBohicJIR2vWdnC8HVgMvSdu2kHAsAwIgKCoHadAJOQlBoGj9CJKkqTIMAkgpDQtA2sQdUQLEYPxswxAPJwPCkNjbCCCiDC0AzsOkFgwYmOI3P4MQtTOGGmB1dzhK1D4NqM7wVaYPtp20HgsTEE0DxeFgYMEMQeAsHLSxUEYwAKAAangmBYSizzHUz/CCCIYjsFIMiCIoKjqNzuhcIYximLYtiGKrdWQEsqCpGh%2BKcNqHwHuYV3WFwXD7JDisi9kbgMJ43htBIITZ7MQyJL76SZFHEztIU5fZEXFTDL7XRR704y55M9jp90DAt/0MJzA30yt3kVdnDMffFxISwKLd6z6KQuuYBsPB7Zwh2kMdp3nRwyioFhCTKLewDIEukjmkk5qBEel02NYpBwvgRAalsBj7F4OMJIcD0Xs9r0LL9/2A32iDUgBsAbrzBlvSGIBoa/3hkjCASAVgEFSDLTGEBsapHRiXEID8SBzwdsIUQ4hXYEI9moHWwsl68CwurVIhsgYHVBtzLeKIZYoKBKgN4O897EAPvsI%2BJ8z4XyvqjTBuNP56G/vPX%2B71MCfWGD9BhwDQGAw3rwSB9hoHSNhn/Ugf0wH7SeuA5hENtFaF0ftCwTDN6mJhuYpYYsKaZ0kEAA%3D%3D%3D)

**Comment by jwellbelove** [comment]
20.24.0
