### ISSUE TITLE
Docs: still referring to singleton support when it was deleted 8 years ago

### ISSUE THREAD

**Issue by florianhumblot** [ETLCPP/etl#507]
The docs still show `singleton` under the patterns category, when it seems to have been removed in 2014:
https://github.com/ETLCPP/etl/commit/bdcf26cde9b4e269c50095a301be9675eb0fd0fb
![image](https://user-images.githubusercontent.com/31630192/153168599-d63f84d1-a043-4efe-86c5-df68982d888d.png)

**Comment by jwellbelove** [comment]
I have no idea why I deleted it.

**Comment by jwellbelove** [comment]
Re-implemented `etl::singleton` with deterministic construction and destruction.
