### ISSUE TITLE
Broken web style

### ISSUE THREAD

**Issue by diggit** [ETLCPP/etl#513]
There seems to be issue with styling of www.etlcpp.com
Not every page is affected
Tested with Firefox 98 (developer build)  and Chromium 99.0.4844.51 with same results.
![intrusive_forward_list](https://user-images.githubusercontent.com/512025/156779834-3ddb004a-d51e-4f8e-b5c2-2c7ea9065d25.png)
![observer](https://user-images.githubusercontent.com/512025/156781084-80a6e7c3-8f3b-4542-a0d9-1ed57b834856.png)
![observer](https://user-images.githubusercontent.com/512025/156781143-35967942-bc4c-4f91-b657-176974efbbb9.png)
![generators_tutorial](https://user-images.githubusercontent.com/512025/156782052-e9ec24e6-4957-49f1-9323-37ae95526d3f.png)

Here is non extensive list of affected pages:
- https://www.etlcpp.com/instance_count.html
- https://www.etlcpp.com/intrusive_forward_list.html
- https://www.etlcpp.com/queue.html
- https://www.etlcpp.com/observer.html
- https://www.etlcpp.com/visitor_tutorial.html
- https://www.etlcpp.com/observer_tutorial.html
- https://www.etlcpp.com/message_tutorial.html
- https://www.etlcpp.com/generators_tutorial.html

Unfortunately I am complete CSS noob, so I am unable to offer fix.

**Comment by jwellbelove** [comment]
The pages aren't coded in raw HTML. I use a WYSIWYG editor to create the web site, but it does seem to have output rendering issues at times. I'll see if I can persuade it to behave!

**Comment by diggit** [comment]
Stumbled on more:
- https://www.etlcpp.com/function.html
- https://www.etlcpp.com/parameter_type.html
