### ISSUE TITLE
Use after move

### ISSUE THREAD

**Issue by mampfes** [ETLCPP/etl#516]
We are using Coverity static code analyzer and found an issue in etl::observer:

https://github.com/ETLCPP/etl/blob/5577170fd268f1618b05773a6bf4d4a25e76d28d/include/etl/observer.h#L250

`n` is effectively moved by std::forward and therefore only valid for the first matching observer. Consecutive observers get a default-initialized instance.

**Comment by jwellbelove** [comment]
Fixed 20.27.0
