### ISSUE TITLE
platform.h uses int for __cplusplus

### ISSUE THREAD

**Issue by wiznillyp** [ETLCPP/etl#520]
In platform.h the line
    `static ETL_CONSTANT int	 cplusplus                        = __cplusplus;`

On my system, int is defined as 16-bits, and __cplusplus is defined as a long (literal with "L" suffix), so the data is truncated and I get a warning about truncation. 

Changing the data type from "int" to "long" fixes it.

**Comment by jwellbelove** [comment]
It may be better to use an `int32_t` to ensure that the size is always correct.
