### ISSUE TITLE
Unused type compiler warning

### ISSUE THREAD

**Issue by shreyasbharath** [ETLCPP/etl#524]
Can we remove this type if not used?

> etl/include/etl/algorithm.h: In function 'typename etl::enable_if<etl::is_pointer<T>::value, void>::type etl::reverse(TIterator, TIterator)':
> etl/include/etl/algorithm.h:298:66: error: typedef 'value_type' locally defined but not used [-Werror=unused-local-typedefs]
     typedef typename etl::iterator_traits<TIterator>::value_type value_type;

**Comment by jwellbelove** [comment]
I've already had a heads-up on this. It should be fixed in the next release.
