### ISSUE TITLE
min_element implementation 

### ISSUE THREAD

**Issue by r2r0** [ETLCPP/etl#529]
After ETL update to the greatest and the latest version I found that UT failed and it is caused by changed implementation of `min_element`.
Of course it is fault in my UT because there was hardcoded assumption about number of comparator calls but it brings to me a topic if actual `min_element` implementation is good/optimal.
In particular `comapre` is called 2 times for vector with 2 elements.

Maybe a `++begin;` just before `while (begin != end)` will be a good idea for improvement.

**Comment by jwellbelove** [comment]
Thanks, I'll take a look.

**Comment by jwellbelove** [comment]
Updated 20.27.2
