### ISSUE TITLE
"Option to make string truncation an error." generates compiling warnings

### ISSUE THREAD

**Issue by Cythraul89** [ETLCPP/etl#545]
The part which should activate the option for string truncation error in platform.h looks like there is a copy paste error:
`
#if ETL_HAS_ERROR_ON_STRING_TRUNCATION
  #define ETL_HAS_ERROR_ON_STRING_TRUNCATION 1
#else
  #define ETL_HAS_ERROR_ON_STRING_TRUNCATION 0
#endif
`

The config file should look like the other options:
`
#if defined(ETL_ENABLE_ERROR_ON_STRING_TRUNCATION)
  #define ETL_HAS_ERROR_ON_STRING_TRUNCATION 1
#else
  #define ETL_HAS_ERROR_ON_STRING_TRUNCATION 0
#endif
`

**Comment by jwellbelove** [comment]
Fixed in 20.28.0
