### ISSUE TITLE
Debounce States conflict with Arduino 

### ISSUE THREAD

**Issue by lekoook** [ETLCPP/etl#547]
The enum for states in debounce.h has an entry "CHANGE".  The Arduino framework has a #define CHANGE used for their interrupts methods.

This appears to conflict with the Arduino framework when both are used together and compilation will fail. The Arduino library version also suffers from the same issue.

A simple solution may be to just rename this to "CHANGED".

**Comment by jwellbelove** [comment]
It's a pain that Arduino seems to have created all of its constants a plain old fashioned #defines, as they do not recognise any scope. The ETL constants are wrapped in structs/enumerations.

The only real solution to stop this happening again and again is to modify the ETL enumerations to non all caps, such as `Change`.

This will of course be a breaking change.

**Comment by lekoook** [comment]
> A person on the ETL Slack group suggested a workaround last year, by including `debounce.h` before `Arduino.h`
> 
> ```
> #include <etl/debounce.h>
> #include <Arduino.h>
> ```

Things can get rather complicated as the project grows, difficult to track the order of the #includes.

The temporary solution I've been using so far is to `#undef CHANGE` just before `#include <etl/debounce.h>` and `#define CHANGE 4` right after. Ugly but I can't think of another solution that isn't a breaking change.

**Comment by jwellbelove** [comment]
Actually I've just realised, looking at the code, that the enumerations are purely internal to the debounce class, so I can name them how I like.

**Comment by jwellbelove** [comment]
Fixed 20.29.2
