### ISSUE TITLE
Install guidelines

### ISSUE THREAD

**Issue by hariudkmr** [ETLCPP/etl#56]
Hi,

Is there any simple guidelines to build and use the ETL Library. 

Regards
Hari

**Comment by jwellbelove** [comment]
There's a page on the website.
https://www.etlcpp.com/setup.html
Let me know if you need more help.

**Comment by jwellbelove** [comment]
I've also started a Slack group to discuss features & issues
https://join.slack.com/t/etlcpp/shared_invite/enQtMjgyMzMxNDg4NTMxLTJmYWI4ZWU0NDFhZDIzYmQ1MWIyNzM3NTRlNjg2OWFhZGE2OWRmYTM5NWVhNjRjNWRkZTllYjY1NjY4NGEyMzg
