### ISSUE TITLE
minmax_push.h/minmax_pop.h includes are missing in string_utilities.h

### ISSUE THREAD

**Issue by ilyapas** [ETLCPP/etl#588]
The header string_utilities.h is using the etl::min function without including the headers "private/minmax_push.h" and "private/minmax_pop.h", as it is done in all other ETL modules where these functions are used. This leads to compile errors on Windows (VS 2022) if min/max macros are defined by the system.

**Comment by jwellbelove** [comment]
Fixed 20.34.0
