### ISSUE TITLE
Automatically define __STDC_LIMIT_MACROS for appropriate compilers

### ISSUE THREAD

**Issue by dhebbeker** [ETLCPP/etl#591]
According to [the manual for using ETL with different compilers](https://www.etlcpp.com/compilers.html) for some compilers it is required to have `__STDC_LIMIT_MACROS` defined. I wonder if it would be an improvement if that macro would be defined automatically by `platform.h` or its dependencies in case such a compiler is detected and the appropriate limit macros are not already defined?

**Comment by dhebbeker** [comment]
Yes, I am compiling for Extended [Embedded C++](http://www.caravan.net/ec2plus/language.html), which is a derivative from C++98.

**Comment by dhebbeker** [comment]
737b0bf6f715941b088c41554d99ed8ff4a50619 is not sufficient to resolve this issue, as often `stdint.h` is included *before* `platform.h`.

**Comment by jwellbelove** [comment]
Thanks, I'll look at that some more.

**Comment by jwellbelove** [comment]
Fixed 20.34.0
