### ISSUE TITLE
Feature request: Helper functions to convert strings to numeric values

### ISSUE THREAD

**Issue by oresk** [ETLCPP/etl#596]
We have the to_string() functions that are really ergonomic, especially when paired with format. 

Having a utility that would do a conversion the other way round would be really usefull addition to ETL.

**Comment by jwellbelove** [comment]
Do you think that the string passed should only contain the numeric string to convert, or should it search for the start and end of the numeric?

i.e. find non-numeric characters.
```
"abc# 123.45*sne"
      ^     ^
```

**Comment by jesseli2002** [comment]
Something like [stoi](https://en.cppreference.com/w/cpp/string/basic_string/stol) in terms of API, perhaps?

**Comment by jwellbelove** [comment]
Including conversion of strings in binary, octal & hex formats?
It may need an explicit base parameter or deduction from the prefix.

```
etl::to_arithmetic<int>("1234", etl::hex());
etl::to_arithmetic<int>("0x1234");
```

**Comment by RallyTronics** [comment]
does anyone still use octal?

**Comment by jwellbelove** [comment]
I'm sure someone does somewhere  :-)

**Comment by jwellbelove** [comment]
- The return type of the functions will be an `etl::optional<T>`, where `T` is an arithmetic type.
- A failure to convert will result in a default constructed `etl::optional<T>`.
- I'm thinking that I should not bother handling stripping off any `0x`, `0X`, `0b` or `0B` prefix from hex and binary strings.
- I'm also thinking that binary, octal and hex strings that are prefixed with `-` are not converted (Or ignored?).
- An attempt to convert a negative decimal string to an unsigned type will also be a failure.
- A `+` prefix to any numeric string will be ignored.
- Whitespace will be ignored.
- Any failure to convert will be submitted to the error handler or thrown as an exception (dependent on configuration)

**Comment by jwellbelove** [comment]
Examples:
`" +123  "` as signed decimal OK
`" -123  "` as signed decimal OK
`" -123  "` as unsigned decimal FAILURE
`" +123  "` as unsigned hex OK
`" 123  "` as signed hex FAILURE
`" -123  "` as signed hex FAILURE
`" 0x123  "` as unsigned hex FAILURE

**Comment by jwellbelove** [comment]
At the moment, `""` is not an error (and returns a default constructed `etl::optional<T>`), but `"-"` or `"+"` _are_ errors.

**Comment by oresk** [comment]
Hm, what would then be a difference between an error and a default constructed `etl::optional<t>`? 
From 4 comments above:

- A failure to convert will result in a default constructed etl::optional<T>.
- Any failure to convert will be submitted to the error handler or thrown as an exception (dependent on configuration)

I was under the impression that a default constructed `etl::optional<T>` indicated an error, and depending on the additional config it can throw an exception. 

Which one it is I would say an empty string would should have the same consequence as any other string that can not be converted.

**Comment by jwellbelove** [comment]
Sorry for my confusing description.
When I said 'errors' I meant a call to `ETL_ASSERT`. A return of a default constructed `etl::optional<T>` is of course a '_failure to convert_' error, so I agree that an empty string should be treated the same as any other '`failure to convert`' error.

**Comment by jwellbelove** [comment]
How important is the ability to have a `constexpr` conversion?
At the moment I am returning `etl::optional<T>`. Unfortunately, `etl::optional` cannot be `constexpr` due to the aligned storage member.

**Comment by jwellbelove** [comment]
Floating point in radixes other than decimal?

**Comment by jwellbelove** [comment]
Added in 20.35.0
[https://www.etlcpp.com/to_arithmetic.html](https://www.etlcpp.com/to_arithmetic.html)

**Comment by oresk** [comment]
Perfect!

Will be using it over the weekend
