### ISSUE TITLE
Feature request: add select1st and select2nd functors

### ISSUE THREAD

**Issue by evantill** [ETLCPP/etl#607]
What do you think of adding [select1st](https://www.boost.org/sgi/stl/select1st.html) and [select2nd](https://www.boost.org/sgi/stl/select2nd.html) functors in ETL library ?

_(I can submit a PR)_

**Comment by jwellbelove** [comment]
Sounds like a nice and simple addition.
If you do a PR, don't forget to use the `ETL_OR_STD::pair` type.

**Comment by evantill** [comment]
I have found two implementations :

- Option A:
```c++
    template <class FirstType>
    struct select1st
    {
      typedef FirstType type;

      template <class T>
      inline const type& operator()(const T& x) const
      {
        return x.first;
      }

      template <class T>
      inline type& operator()(T& x)
      {
        return const_cast<type&>(x.first);
      }
    };
```

- Option B:
```c++
    template<typename T>
    struct Select1st {
      typedef typename T::first_type type;

      inline type& operator()(T& x) const
      {
        return x.first;
      }

      inline const type& operator()(const T& x) const
      {
        return x.first;
      }
    };
```

My preferred option is option B.

Which one to use in ETL ?

**Comment by jwellbelove** [comment]
I prefer option B.
Option A looks odd as it seems to require type information that was already implied in the function name.

**Comment by evantill** [comment]
Perfect _(I also prefer option B)_.

**Comment by evantill** [comment]
@jwellbelove can we close this issue ?

**Comment by jwellbelove** [comment]
To be included in next release.
