### ISSUE TITLE
Auto detect builtins for type traits

### ISSUE THREAD

**Issue by jwellbelove** [ETLCPP/etl#609]
Add the ability to use builtins for type traits if they exist.

**Comment by jputcu** [comment]
Related to #608, I tried to enable the custom traits, but this gave me lots of errors.
To detect `is_trivially_copyable` on `AVR` I tried the following on compiler explorer. Newer compiler versions support the  `__has_builtin`, but older I needed to fallback to actually detecting.

~~~~
int main()
{
    #if defined(__has_builtin)
        // GCC >= 10.3.0?
        return __has_builtin(__is_trivially_copyable)?1:2;
    #else
        struct A { int a; };
        return __is_trivially_copyable(A)?3:4;
    #endif
}
~~~~
