### ISSUE TITLE
Feature request: addition of etl::expected

### ISSUE THREAD

**Issue by jputcu** [ETLCPP/etl#615]
Could it be possible to add `etl::expected`, matching the [c++23 std::expected](https://en.cppreference.com/w/cpp/utility/expected).
Because the lack of exceptions on my AVR platform, I have used `etl::variant` for this, but having a more standard way would be better.
This could be a replacement of `etl::result`.

**Comment by jwellbelove** [comment]
Thanks, I'll take a look at that

**Comment by jwellbelove** [comment]
Implementation of `etl::unexpected` in 20.35.0

**Comment by jputcu** [comment]
I was planning to use this, but noticed only `unexpected` was provided.
Looking around I found two nice, active, alternatives:

1. https://github.com/martinmoene/expected-lite
2. https://github.com/TartanLlama/expected

To not reinvent the wheel it would be nice if we could use them, but I quickly run into `AVR` limitations, e.g. missing `utility` header. Although `etl` probably provides everything required.
Could it be possible to provide a layer to satisfy the `std` library?

This layer would allow more lightweight C++ libraries to be used, e.g. `https://github.com/boost-ext/sml`.

**Comment by jwellbelove** [comment]
The trouble with the last thing I said about headers is that the compiler would not be able to distinguish which template library (STL or ETL) to use when it sees something like `#include <algorithm>`.

**Comment by jputcu** [comment]
I think all `etl` headers end with `.h`, so we could perhaps a directory with the official headers which forward to the `.h` headers and alias the namespace?

**Comment by jwellbelove** [comment]
I think the problem is that if you did that, the compiler will will probably still find its own headers before the ETL's.

`#include <algorithm>` <<< I think the compiler will choose its own <algorithm> header first.

**Comment by jwellbelove** [comment]
With GCC it seems you can use `-nostdinc++` as a compiler option. I don't know about other compilers.

**Comment by jwellbelove** [comment]
Fixed 20.35.12
