### ISSUE TITLE
[bug] incorrect computation of find_next in bitset

### ISSUE THREAD

**Issue by Chiraffollo** [ETLCPP/etl#617]
The method find_next returns erroneous result if the starting position is larger or equal the number of bits in the underlying type, e.g., for bitset<64, uint8> method find_next only works for starting position < 8.
Additionally, the class may not compile if starting position is larger than bits in unsigned.

Example:
```
etl::bitset<64> bs1(0xC000'0000'0000'0031ULL);
size_t bs1fnt1 = bs1.find_next(true, 10);
size_t bs1fnt2 = bs1.find_next(true, 59);
CHECK_EQUAL(62U, bs1fnt1);
CHECK_EQUAL(62U, bs1fnt2);
```
Result:
bs1fnt1: `Expected 62 but was 54`
bs1fnt2: `Expected 62 but was 18446744073709551615`

**Comment by jwellbelove** [comment]
Fixed in next release
