### ISSUE TITLE
Support external memory buffer for etl::pool

### ISSUE THREAD

**Issue by wuyuanyi135** [ETLCPP/etl#619]
Some devices like ESP32 may provide an external memory (PSRAM) to expand the RAM capability. It would be useful if the `etl::pool` can manage an externally-allocated array of `uint8_t`, so that the use case of external memory could be covered.

**Comment by jwellbelove** [comment]
I forgot that there already is what you want.

`etl::pool_ext`

**Comment by wuyuanyi135** [comment]
Many thanks. I didn't find this on the documentation so I missed it as well.

**Comment by jwellbelove** [comment]
I'll check the documentation and update.
