### ISSUE TITLE
Integer type for scaled rounding functions is too small.

### ISSUE THREAD

**Issue by dhebbeker** [ETLCPP/etl#620]
I have an issue with the scaled rounding functions: All functions accept the scaling as `size_t` parameter. My compiler translates `size_t` to `uint16_t` (target: AVR ATXMega). Also `SCALING` is casted to a 32bit integer type `scale_t`. This is quite restrictive as I would like, for example, to scale by 1000000.

**Comment by jwellbelove** [comment]
Fixed in next release.
