### ISSUE TITLE
Online documentation lists etl::vector::emplace() but actual function is etl::vector::emplace_back()

### ISSUE THREAD

**Issue by vietjtnguyen** [ETLCPP/etl#635]
Online documentation screenshot at https://www.etlcpp.com/vector.html:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/2792002/202552541-1c01a171-ce10-4874-85a6-069d8aba4bfc.png">

Function definition:

https://github.com/ETLCPP/etl/blob/3623ba5b38e6fb3003238b6967a6a25ce096f5ab/include/etl/vector.h#L455-L535

**Comment by jwellbelove** [comment]
Updated.
