### ISSUE TITLE
Profile settings from docs that does not exist in code

### ISSUE THREAD

**Issue by aunsbjerg** [ETLCPP/etl#644]
I am looking into using ETL as a Zephyr module, which means mapping ETL profile settings to Zephyr Kconfig settings. I found some settings that are mentioned in the [docs](https://www.etlcpp.com/macros.html) but that doesn't seem to exist in code anymore.

* `ETL_STRING_TRUNCATION_IS_ERROR`
* `ETL_MESSAGES_ARE_VIRTUAL`
* `ETL_USE_MEM_BUILTINS`

The last one is added to compile definitions in test projects, but doesn't seem to have any impact on the actual code. I might be missing something there.

**Comment by jwellbelove** [comment]
It looks like I changed it to `ETL_ENABLE_ERROR_ON_STRING_TRUNCATION` from 20.26.0.
`ETL_MESSAGES_ARE_VIRTUAL` is no more as messages are always virtual now.
`ETL_USE_MEM_BUILTINS` has also gone as an experimental feature that didn't work very well.
I'll update the documentation.

**Comment by jwellbelove** [comment]
And I'll update the CMake files.

**Comment by rovo89** [comment]
@jwellbelove https://www.etlcpp.com/string.html still mentions only `ETL_STRING_TRUNCATION_IS_ERROR`.

**Comment by jwellbelove** [comment]
Thanks

**Comment by rovo89** [comment]
Still so, I think you have just replace one out of three occurences. ;)
