### ISSUE TITLE
Improve default is_constructible, is_copy_constructible, is_move_constructible

### ISSUE THREAD

**Issue by aBraM-aBraM** [ETLCPP/etl#646]
The default implementation (the ones that exist if the user only defined ETL_NO_STL) can be improved to check for more than pointers and integral values. They don't require intrinsic compiler functions and have implementations in the cpp standard

**Comment by jwellbelove** [comment]
Do you want to raise a PR?

**Comment by aBraM-aBraM** [comment]
> Do you want to raise a PR?

yeah I've already solved this just a minute :)
