### ISSUE TITLE
Suggestion to modify location of header files

### ISSUE THREAD

**Issue by DrChr** [ETLCPP/etl#65]
Issue to track work on a modified directory structure to e.g. reduce name collisions for header files. Previously discussed in #64, but better off as a separate issue.

Background: ETL currently has .h and .cpp files in etl/src/. If your project e.g. include other 3rd party libraries, containing e.g. queue.h, there's a risk of name collision with e.g. `etl/src/queue.h`.

Possible solution: Move ETL headers to: `etl/include/etl/` and let the project add etl/include/ to it's include paths. The source code would then include "queue.h" by doing:   ` #include "etl/queue.h"`

**Comment by jwellbelove** [comment]
I've created a tag 10.21.2 as the last Arduino compatible version, due to Arduino's very specific directory layout specifications. The new layout will start from 11.0.0

**Comment by jwellbelove** [comment]
The new layout has been pushed to master.

**Comment by DrChr** [comment]
Thanks. I gave it a very quick look/test and it seems to work. :-)

Some notes follows now. I cloned master to `<repo-root>/lib/etl-cpp/` and added `<repo-root>/lib/etl-cpp/include/` to the include paths. Then I created a source file that used

    #include "etl/queue.h"

I got an compile error for my "etl_profile.h", as it since before said

    #include "profiles/gcc_generic.h"

but to make it work I just modified it to

    #include "etl/profiles/gcc_generic.h"

So existing "etl_profile.h":s will likely need a quick change, once per project.

As a minor issue, I looked in e.g. 'queue.h', which includes eg:

    #include "container.h"

I'm wondering if e.g. the include directive should instead read e.g.
 
    #include "etl/container.h"

This would make it clearer that it's an internal etl header that's used.
But I don't _think_ it's needed though, I just don't remember what the standard says. I did check GCC for which it's not needed. I.e., according to as https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html, GCC will search for "container.h" first in the folder that contains queue.h.

**Comment by jwellbelove** [comment]
Actually,n container.h is not an internal header.

**Comment by DrChr** [comment]
You're right, "internal" is incorrect. What I meant was that it's just an ETL header. 
Note: I've updated my comment text above to avoid confusing the issue.
