### ISSUE TITLE
Add result<T, void> specialization

### ISSUE THREAD

**Issue by aBraM-aBraM** [ETLCPP/etl#651]
Some errors don't have additional data (think of is_odd(int num) kind of function).

Add a specialization for void error type with default ctor creating an error

**Comment by jwellbelove** [comment]
If the error type is `void`, what to do about the member functions

```
const TError& error() const
TError&& error()
```

**Comment by jwellbelove** [comment]
Or do you expect the `error()` functions to be not implemented, like `value()` is not implemented for `etl::result<void, TError>`

**Comment by aBraM-aBraM** [comment]
I believe it should not be implemented just as result<void, T> doesn't
implement value().

It should also be noted and documented and the user has the responsibility
to use is_value / is_error appropriately.

I feel good about it as all errors related to this are compile-time.

**Comment by jwellbelove** [comment]
Fixed 20.35.9
