### ISSUE TITLE
Warning when used with CMake

### ISSUE THREAD

**Issue by flaviut** [ETLCPP/etl#653]
When I use this as a dependency in my CMake project (with CPM/FetchContent), I get the following warning: "Version string HEAD-HASH-NOTFOUND retrieved with git describe is invalid".

This is because etl [tries to get the version number with Git first, before falling back to `version.txt`](https://github.com/ETLCPP/etl/blob/master/CMakeLists.txt#L9-L12).

Would it be reasonable to wrap [this in a `PROJECT_IS_TOP_LEVEL` flag](https://cmake.org/cmake/help/latest/variable/PROJECT_IS_TOP_LEVEL.html)? If ETL is being built standalone or on older versions of CMake, first try and get the version from git. If ETL is being build as a subdirectory, first try and get the version `version.txt`. In both cases, fall back to the other on failure.

**Comment by jwellbelove** [comment]
That sounds like a reasonable change. Are you able to do the change and create a pull request for this?

**Comment by jwellbelove** [comment]
Fixed 20.35.9
