### ISSUE TITLE
vector emplace_back not returning a reference

### ISSUE THREAD

**Issue by W4RH4WK** [ETLCPP/etl#656]
Since C++17, `std::vector::emplace_back` returns a reference to the constructed element.

I find this rather handy, what do you think about adding this to etl as well?

**Comment by jwellbelove** [comment]
Yes, that sounds a good idea.

**Comment by jwellbelove** [comment]
I think that this can be applied to several of the ETL's containers.

**Comment by W4RH4WK** [comment]
Yes, I've seen `std::optional` having the same feature. I'll look into that over the weekend and will put together a PR.

**Comment by jwellbelove** [comment]
There's `vector`, `deque`, `list` and forward_list (maybe more) and also `emplace_front`.

**Comment by jwellbelove** [comment]
There's `vector`, `deque`, `list` and `forward_list` (maybe more) and also `emplace_front`.

**Comment by jwellbelove** [comment]
If you want to do the changes, don't forget to update the units tests.
