### ISSUE TITLE
Add `reset()` method to `etl::optional`

### ISSUE THREAD

**Issue by ArekSredzki** [ETLCPP/etl#66]
`std::optional` provides a convenient `reset()` method which is not currently available in the etl counterpart.

Currently users must copy a newly constructed instance of `etl::optional<T>` to achieve the same result.

P.S. Thanks for the great library!

**Comment by jwellbelove** [comment]
OK, I'll take a look at that. Sounds like a simple addition.

**Comment by jwellbelove** [comment]
Done

**Comment by ArekSredzki** [comment]
Awesome, thanks @jwellbelove !
