### ISSUE TITLE
Problem with move assignement for vector_ext

### ISSUE THREAD

**Issue by r2r0** [ETLCPP/etl#665]
Is it expected that move assignement for vector_ext does not work in a way as in code below?

Compiled on x86 and GCC 12.2 with C++ 17 as C++ version

https://godbolt.org/z/esKcYd5e1

```c++
#include <iostream>

#include "etl/array.h"
#include "etl/vector.h"


int main()
{
    etl::array<uint8_t, 1> data1 {42};
    etl::vector_ext<uint8_t> v1 {data1.begin(), data1.size()};

    etl::array<uint8_t, 2> data2 {43, 44};
    etl::vector_ext<uint8_t> v2 {data2.begin(), data2.size()};

    std::cout << "v1.begin() = " << static_cast<void*>(v1.begin()) << "  v1.capacity() = " << v1.capacity() << '\n';
    std::cout << "v2.begin() = " << static_cast<void*>(v2.begin()) << "  v2.capacity() = " << v2.capacity() << "\n\n";

    v1 = std::move(v2);
    std::cout << "v1 = std::move(v2);\n";
    std::cout << "v1.begin() = " << static_cast<void*>(v1.begin()) << "  v1.capacity() = " << v1.capacity() << "\n\n";

    v1 = etl::vector_ext<uint8_t>(data2.begin(), data2.size());
    std::cout << "v1 = etl::vector_ext<uint8_t>(data2.begin(), data2.size());\n";
    std::cout << "v1.begin() = " << static_cast<void*>(v1.begin()) << "  v1.capacity() = " << v1.capacity() << "\n\n";

    return 0;
}
```

Output is:
```
v1.begin() = 0x7ffecd5bb61c  v1.capacity() = 1
v2.begin() = 0x7ffecd5bb61e  v2.capacity() = 2

v1 = std::move(v2);
v1.begin() = 0x7ffecd5bb61c  v1.capacity() = 1

v1 = etl::vector_ext<uint8_t>(data2.begin(), data2.size());
v1.begin() = 0x7ffecd5bb61c  v1.capacity() = 1
```

**Comment by jwellbelove** [comment]
When you move an `etl::vector_ext` you only move the elements, but the pointer to the external storage is not copied over. This was done by design, as it would result in orphaned blocks of memory. 

As in your example, there is no mechanism for tracking whether `data2` is in use or not, which could cause some interesting bugs if it was got wrong. This is why I decided it was safer to not move the buffer pointer.

The STL vector can copy pointers because the vector code will ensure proper handling of allocation and deallocation of memory.

**Comment by r2r0** [comment]
Thanks, this answer explains the topic completely.

**Comment by jwellbelove** [comment]
I remembered another reason for why ETL vectors cannot be moved like `std::vector`.
It is not possible to move an internally buffered vector to an externally buffered vector and vice-versa.

```
etl::vector<int, 10> v1;

int buffer[10];
etl::vector_ext<int> v2(buffer);

v1 = std::move(v2); // v1 cannot 'steal' v2's buffer as then v1 would become externally buffered and the internal buffer would be 'lost'.
or
v2 = std::move(v1); // v2 cannot 'steal' v1's buffer as then v1 and v2 would share a buffer.
```

If the code in `etl::ivector` were modified to indicate whether the derived instance is internally or externally buffered, then the move would do different things according to type.
