### ISSUE TITLE
Compilation error in optional.h line 405

### ISSUE THREAD

**Issue by lekoook** [ETLCPP/etl#675]
Since commit 8ddf0935d3f11ddbc6508f29dc62cbaa72f1b9f6, line 405 in optional.h is causing the following error during compilation:

```
error: expected unqualified-id before 'template'
```

Removing `ETL_CONSTEXPR20_STL` appears to prevent that error.

**Comment by jwellbelove** [comment]
The `ETL_CONSTEXPR20_STL` should be after the `template` line, not before it.

**Comment by jwellbelove** [comment]
Fixed 20.36.0
