### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by valentinec91** [ETLCPP/etl#687]
Hello John! 

I have a build issue on xpack-arm-none-eabi-gcc v 11.3.1 from [here](https://xpack.github.io/blog/2022/08/28/arm-none-eabi-gcc-v11-3-1-1-1-released/).

I am using -std=c++20

Seems like compiler don't like *constexpr* keyword before *template* keyword and produces such build error:
```
......
[build] In file included from D:/lib/etl/include/etl/private/delegate_cpp11.h:56,
[build]                  from D:/lib/etl/include/etl/delegate.h:37,
[build]                  from D:/Projects/Electronics/stm32-from-template/system/workers.hpp:4,
[build]                  from D:/Projects/Electronics/stm32-from-template/app/usb_events.cpp:14:
[build] d:\lib\etl\include\etl\optional.h:404:5: error: expected unqualified-id before 'template'
[build]   404 |     template <typename ... TArgs>
[build]       |     ^~~~~~~~
[build] ninja: build stopped: subcommand failed.
.......
```

this is the problem place:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/19186190/232576596-e4597ee3-e749-4ba5-8920-cd924dcb6bf4.png">

After swapping lines 403 and 404 build is fine.

Suggested solution is swap these line, maybe in other identical places too.

Best regards!

**Comment by jwellbelove** [comment]
Thanks

**Comment by jwellbelove** [comment]
Will be fixed in next release
