### ISSUE TITLE
etl::span copy constructor doesn't compile when types are not the same

### ISSUE THREAD

**Issue by fermentedfly** [ETLCPP/etl#691]
As far as I can tell the copy constructor implementation in span.h:627 changed from 20.35.11 to 20.35.12

```
 template <typename U, size_t N>
    ETL_CONSTEXPR span(const etl::span<U, N>& other) ETL_NOEXCEPT
      : pbegin(other.pbegin)
      , pend(other.pend)
    {
    }
```

I have a rare case where T is `char const` and U is `char`
This was fine in previous versions but now does not compile since `other.pbegin` & `other.pend` are accessed directly.

I'm not sure if my usecase was ever intended behavior or not.

**Comment by jwellbelove** [comment]
Fixed 20.36.0
