### ISSUE TITLE
circular_buffer - fill() method

### ISSUE THREAD

**Issue by falkd** [ETLCPP/etl#694]
I expected that the fill() method of the circular_buffer does also modifie the read/write iterators of the buffer, but it only fills the buffer. 
Is this the intended function or may be an issue?

**Comment by jwellbelove** [comment]
I looked back at the documentation for etl::circular_buffer
For `fill()` it says _Fill the _current_ size of the buffer with value_.

It overwrites the _current_ contents of the buffer, so if the buffer is five elements long, those five elements will be replaced by the fill value.

Example:

```
std::vector<std::string> input{ "0", "1", "2", "3", "4" };
std::vector<std::string> expected{ "9", "9", "9", "9", "9" };

etl::circular_buffer<std::string, 10> data;

data.push(input.begin(), input.end());
```
Buffer: `"0", "1", "2", "3", "4"`
```
data.push("5");
```
Buffer: `"0", "1", "2", "3", "4", "5"`
```
data.pop();
```
Buffer: `"", "1", "2", "3", "4", "5"`
```
data.fill("9")

```
Buffer: `"", "9", "9", "9", "9", "9"`
```
data.push("6");
```
Buffer: `"", "9", "9", "9", "9", "9", "6"`
```
data.pop();
```
Buffer: `"", "", "9", "9", "9", "9", "6"`

**Comment by falkd** [comment]
You are right, when reading the documentation it does what it should. Thank you.
