### ISSUE TITLE
Reduce RAM overhead of etl::queue<>

### ISSUE THREAD

**Issue by DrChr** [ETLCPP/etl#70]
On my Cortex-M4 target the I get ```sizeof(etl::queue<char,16>) == 40``` which means a significant overhead. Perhaps it'd make sense to add a "cheaper" queue type?

Some possibilities:
- Add option to remove  ```etl::debug_count construct_count;```
- Allow user to set the  ```size_type```, in my case I'd be happy using int16_t for the size. Perhaps as an extra template parameter. Or perhaps via a macro the user can provide for the "default size type" to use for queue(s).
- _Perhaps_ allocate data directly in the queue, instead of using indirection
- Currently a ```counter``` data field is used. The count could instead maybe be specified to as 'fast' (keep an up to date count) or 'slow' (calculate on the fly).

Partially related:
- The queue currently uses 'placement new' to insert the values. It could be a simple copy for PODs. 

While on the topic of the queue, it might make sense to align the interface with that of the STL's queue:  http://www.cplusplus.com/reference/queue/queue/   This should perhaps be a different issue though.

**Comment by jwellbelove** [comment]
Queues now have a 'memory model' template parameter to reduce resource size.
