### ISSUE TITLE
Calling accept on etl::variant visits a copy instead of the original object

### ISSUE THREAD

**Issue by eloisesko** [ETLCPP/etl#710]
I previously made a request to enable visiting a `const` `etl::variant`, which was implemented in 20.36.0. However, it appears that this implementation has introduced a new issue when calling the `accept` function on the `etl::variant`.

The function now visits a copy of the variant instead of the original object, which is likely a result of the workaround for MSVC introduced for visiting a `const` `etl::variant`. This behavior is not desired, as it may cause unintended side effects and doesn't work with non-copyable objects.

**Comment by jwellbelove** [comment]
Fixed 20.37.0
