### ISSUE TITLE
etl::variant (variant_varadic) default constructed state

### ISSUE THREAD

**Issue by fermentedfly** [ETLCPP/etl#716]
Hi,

if I declare a variant e.g. `etl::variant<A, B>` and default construct it, it seems the variant is in a state indicating it contains an object of type `A`.
I think this is related to the default constructor initializing `type` to 0 instead of  variant_npos  (variant_varadic.h:534)

Regards,
Manuel

**Comment by jwellbelove** [comment]
Fixed 20.37.0
