### ISSUE TITLE
variant_pool create method should use std::forward

### ISSUE THREAD

**Issue by pwsoftwaredesigns** [ETLCPP/etl#725]
The following line in variant_pool.h:

https://github.com/ETLCPP/etl/blob/98c74bfda874f6a659bd95f8451b17d321d0b4e3/include/etl/variant_pool.h#L166

Should be modified as follows:

`return base_t::template create<T>(std::forward<Args>(args)...); `

In order to support move-only types.

**Comment by jwellbelove** [comment]
Fixed 20.37.0
