### ISSUE TITLE
Etl::equal specialisation for etl::span is deduced wrongly when using STL and CPP20

### ISSUE THREAD

**Issue by StjerneIdioten** [ETLCPP/etl#737]
Hi,

Just a little something that does end up giving the right behaviour at the end, but through what I would assume to be the wrong path.

When using `etl::equal` for `etl::span`, added in 20.35.12, we end up calling the 4-parameter version of `etl::equal` taking four iterators.

https://github.com/ETLCPP/etl/blob/b0153bdff75eb54d18c9c96fca70364426f9e6d3/include/etl/span.h#L890-L897

The problem is that when compiling with **ETL_USING_STL** and **ETL_USING_CPP20** no such function is available in _algorithm.h_. What is available however is the 4-parameter function taking a predicate as the fourth parameter. This then just delegates that call to `std::equal`, which then ends up in the correct place being called with four iterators as I assume it fails on the fourth argument not fitting with a predicate.

https://github.com/ETLCPP/etl/blob/b0153bdff75eb54d18c9c96fca70364426f9e6d3/include/etl/algorithm.h#L562C1-L578

So the code doesn't fail, at least not on MSVC. I haven't checked any other compilers to see if they also end up with the correct deduction for the function. But in any case it does not seem like an intentional path that it ends up taking 😄

**Comment by jwellbelove** [comment]
Fixed 20.37.3
