### ISSUE TITLE
Feature request: Get time when next timer will expire etl::callback_timer

### ISSUE THREAD

**Issue by ronaldd2** [ETLCPP/etl#744]
It would be nice to have a way to get the time before the next timer will expire so we know how long a task/micro can sleep. 
Effectively just return active_list.front().delta. 
There could be some side effects when a timer interval is changed but this really depends on the application.

**Comment by jwellbelove** [comment]
Added 20.38.0

**Comment by ronaldd2** [comment]
@jwellbelove  thank you very much  👍
