### ISSUE TITLE
warning about constexpr in array.h

### ISSUE THREAD

**Issue by MickroC** [ETLCPP/etl#755]
I get the following warning (etl version 20.38.1):

> array.h(137): warning: use of this statement in a constexpr function is a C++14 extension [-Wc++14-extensions]

Backround:
I am restricted to C++11 and the warning appears only if `ETL_NO_CHECKS` is not defined. Since C++11 is severely limited in terms of the content of `constexpr` functions, I think the expansion of `ETL_ASSERT` is not allowed in this case.

As far as possible I try to treat warnings like errors. Is it possible to add another check about the C++ version at this point?

**Comment by jwellbelove** [comment]
Fixed 20.38.2
