### ISSUE TITLE
Move assignment not working for non-empty containers

### ISSUE THREAD

**Issue by somaveszelovszki** [ETLCPP/etl#758]
The move assignment is not working properly for some container types if the target is not empty.
Affected container types: priority_queue, set, multiset.
Solution: clear() needs to be called in these move assignment functions before adding the new elements to the target container.
I already have the fix locally, but I don't have permission to push my branch and create a PR.

**Comment by jwellbelove** [comment]
I think you have to fork the project to do a PR.

**Comment by somaveszelovszki** [comment]
Thank you, I forked the project and created a PR.

**Comment by jwellbelove** [comment]
Fixed 20.38.2
