### ISSUE TITLE
hash.h assertions fail with MSP430 microcontroller

### ISSUE THREAD

**Issue by ReneCanadian** [ETLCPP/etl#760]
When including `etl::span` the following assertion in `hash.h` fails:
 ETL_STATIC_ASSERT(sizeof(size_t) >= sizeof(wchar_t), "size_t smaller than type");

**Comment by jwellbelove** [comment]
This was fixed in `20.38.0`

**Comment by ReneCanadian** [comment]
Awesome thanks!!!
