### ISSUE TITLE
version.h mismatch in tag 20.38.1

### ISSUE THREAD

**Issue by CurtisAMU** [ETLCPP/etl#763]
version.h in the tag 20.38.1 archive etl-20.38.1.zip defines
```
#define ETL_VERSION_MAJOR 20
#define ETL_VERSION_MINOR 38
#define ETL_VERSION_PATCH 0
```
I'd expect `#define ETL_VERSION_PATCH 1`.

**Comment by jwellbelove** [comment]
I have deleted 20.38.1 as it did not have the stated fixes
