### ISSUE TITLE
Change assert to ETL_ASSERT in memory.h

### ISSUE THREAD

**Issue by Cythraul89** [ETLCPP/etl#769]
memory.h is the only file where the standard assert function is used.
Not sure if it's possible to change them to ETL_ASSERT

**Comment by jwellbelove** [comment]
The `assert`s are in places that should never be executed, except for a major bug in the ETL.
I use the `ETL_ASSERT`s for runtime errors that could actually occur.

**Comment by Cythraul89** [comment]
Thanks for the fast response.
I was just confused because I found only two normal `asserts `and all other were `ETL_ASSERT`.
