### ISSUE TITLE
endian enum_type produces useless-cast warnings

### ISSUE THREAD

**Issue by digimokan** [ETLCPP/etl#780]
In endianness.h, the int `static_cast`s to the `ETL_ENDIAN_LITTLE/BIG/NATIVE` values in `enum enum_type` (inside `struct endian`) are producing warnings when compiled with `-Wuseless-cast`in gcc.

It looks like the warnings go away when the casts are changed to functional casts (e.g. `int{ETL_ENDIAN_LITTLE}`), but that only works with C++11. I can't tell, but it looks like the literal values would be of type `int` anyway?

**Comment by jwellbelove** [comment]
Fixed 20.38.8
