### ISSUE TITLE
`etl::multi_span::iterator::operator *()` fails if first `span` is empty

### ISSUE THREAD

**Issue by dhebbeker** [ETLCPP/etl#781]
If the first `etl::span` of an `etl::multi_span` is empty, the first call to `etl::multi_span::iterator::operator*()` will return a NULL pointer.

In contrast, if another `span` in the `multi_span` is empty (not the first), then `etl::multi_span::iterator::operator ++()` will check for empty `span`s and skip them correctly.

I suggest to add an appropriate check and skip in `etl::multi_span::iterator::iterator(span_list_iterator, span_list_iterator)`.

**Comment by jwellbelove** [comment]
Fixed 20.38.7
