### ISSUE TITLE
u8string

### ISSUE THREAD

**Issue by wh1t3lord** [ETLCPP/etl#786]
Hello and thanks for putting so much effort into this project!

By the way, it would be perfect to see a header file of u8string.  

Is any reason for not adding this? Maybe I don't know something, because I tried to find explanation related to this class and the result was nothing. For that case I want to ask about possible adding of u8string class. Because in C++20 we have the char8_t type and it's separated to char. 

I think it is a reasonable thing today, library has u16string, u32string and wstring, but u8string doesn't exist.

**Comment by jwellbelove** [comment]
It should be pretty easy to add `etl::u8string`. I'll look into it.

**Comment by jwellbelove** [comment]
Added 20.38.7
