### ISSUE TITLE
Request to prioritize ETL_TARGET_OS_* for mutex selection

### ISSUE THREAD

**Issue by JoeBenczarski** [ETLCPP/etl#800]
I'd like to request that mutex.h prioritizes the ETL_TARGET_OS_* macros for selecting the mutex header. I have a use-case where I want to use FreeRTOS mutexes, but I don't want to define ETL_NO_STL since it will cause build errors due to multiple definitions of STL classes.

Thanks for considering!

**Comment by jwellbelove** [comment]
Fixed 20.38.10
