### ISSUE TITLE
No file `test_atomic_gcc.cpp`

### ISSUE THREAD

**Issue by multivac61** [ETLCPP/etl#81]
https://github.com/ETLCPP/etl/blob/1d6a1109fc733e495c842451e3e5842507dac0cf/test/CMakeLists.txt#L135

There is no file named `test_atomic_gcc.cpp`. Shouldn't this line rather be
```
list(APPEND TEST_SOURCE_FILES "test_atomic_gcc_sync.cpp") 
```
?

**Comment by jwellbelove** [comment]
Updated
