### ISSUE TITLE
Implement SAE J1850 CRC8

### ISSUE THREAD

**Issue by drewr95** [ETLCPP/etl#811]
I've recently needed to use the j1850 crc8 checksum and figured this library might find use for it as well.

When it comes to SAE, finding detailed public information (free) isn't really easy to come by.  [This post on SO can give some insight.](https://stackoverflow.com/questions/38639423/understanding-results-of-crc8-sae-j1850-normal-vs-zero)

**Comment by jwellbelove** [comment]
Pull request merged
