### ISSUE TITLE
Multiple variable shadowing warnings in private/bitset_new.h

### ISSUE THREAD

**Issue by digimokan** [ETLCPP/etl#823]
When compiling with -Wshadow, there are multiple warnings in private/bitset_new.h.

There is one warning for the `lsb` variable shadowing:

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L643

And the rest of the warnings come from `value` variable shadowing:

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L190

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L532

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L766

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L974

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L1038

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L1048

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L1855

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L1926

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L2642

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L2651

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L2760

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L3530

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L3520

https://github.com/ETLCPP/etl/blob/master/include/etl/private/bitset_new.h#L3641

**Comment by jwellbelove** [comment]
I'm currently refactoring `bitset_new.h`, so I'll look at these changes while I'm at it.

**Comment by jwellbelove** [comment]
Fixed 20.38.11
