### ISSUE TITLE
Fixed Extent etl::span shouldn't allow default constructor

### ISSUE THREAD

**Issue by omar-droubi** [ETLCPP/etl#825]
With recent ETL versions, it's allowed to to create a default Fixed Extent etl::span<T, S>.

This causes a problem because the member function size() returns "Extend" even though the data is nullptr. This different from old behavior were there two pointers "mbegin, mend" and the size was the difference.

Fixed Extent etl::span should be considered as a view to existing data.

Current std::span doesn't allow default construction, so it would make sense that etl does the same.

```cpp
etl::span<uint8_t, 10> x; // compiles
std::cout << x.size() << std::endl; // prints 10 but x is nullptr
```
```cpp
std::span<uint8_t, 10> x; //doesn't compile
```
Options:
- Remove the default constructor
- Modify size() to check for nullptr.
```cpp
    ETL_NODISCARD ETL_CONSTEXPR size_t size() const ETL_NOEXCEPT
    {
      return pbegin == ETL_NULLPTR ? 0 : Extent;
    }
```

**Comment by jwellbelove** [comment]
Fixed 20.38.11
