### ISSUE TITLE
Possible bug on assign of etl::array

### ISSUE THREAD

**Issue by cuim96** [ETLCPP/etl#829]
On assign method of etl/array.h

template <typename TIterator>
void assign(TIterator first, const TIterator last, parameter_t value)
{
  // Copy from the range.
  iterator p = etl::copy(first, last, begin()); // shouldn't this also be etl::copy_s? What happens if range [first, last[ is bigger than [begin(), end()[?

  // Initialise any that are left.
  etl::fill(p, end(), value); // what happens here if p > end()?
}

**Comment by jwellbelove** [comment]
Fixed 20.38.11
