### ISSUE TITLE
Make strong typedefs able to be constexpr

### ISSUE THREAD

**Issue by drewr95** [ETLCPP/etl#838]
I noticed that the strong typedefs _ETL_TYPEDEF_ doesn't use constexpr when I think it could.  I think this could additionally be applied to the custom enum macro and user type macros as well.

Example:
```c++
ETL_TYPEDEF(float, seconds);
constexpr seconds duration{1.0F};
``` 

Trying to constexpr a strong typedef results in a compilation error:

> error: constexpr variable cannot have non-literal type 'const seconds' (aka 'const type_def<seconds_tag, float>')

**Comment by jwellbelove** [comment]
Fixed 20.38.11
