### ISSUE TITLE
Strange expression in volatile atomic operator --

### ISSUE THREAD

**Issue by Chuvi-w** [ETLCPP/etl#855]
https://github.com/ETLCPP/etl/blob/a98d387a118281eb6bcd45ebbbf002ddc6626fe7/include/etl/atomic/atomic_gcc_sync.h#L170
Probably
` __atomic_fetch_sub(&value, 1), etl::memory_order_seq_cst;`
should be replaced to
` __atomic_fetch_sub(&value, 1, etl::memory_order_seq_cst);`

I doubt this is a mistake. That's why I created an issue, not a pull request.

**Comment by jwellbelove** [comment]
You are correct, it is a mistake. I'm surprised that it doesn't show up in the syntax check test script.

**Comment by jwellbelove** [comment]
Fixed 20.38.11
