### ISSUE TITLE
Bug: queue move-assignment is not compiling

### ISSUE THREAD

**Issue by enbyted** [ETLCPP/etl#885]
For queue type the move assignment is defined as such:
```c++
queue& operator=(queue&& rhs)
{
  if (&rhs != this)
  {
    base_t::move_clone(rhs);
  }

  return *this;
}
```

There is a missing `etl::move()` around the rhs, which causes the r-value reference to be converted to l-value reference, which fails compilation.

**Comment by jwellbelove** [comment]
Fixed 20.38.12
