### ISSUE TITLE
Supporting -mlarge compilation for MSP430

### ISSUE THREAD

**Issue by ReneCanadian** [ETLCPP/etl#913]
Hi!

The issue concerns building projects for 20 bit architecture for MSP430s. Currently anything that uses `integral_limits.h`  for example `span.h` will crash. The work around that I found to this is adding a definition for int_20 in `integral_limits.h`
```
     template<>
     struct integral_limits<__int20 unsigned> {
         static constexpr __int20 unsigned max = 0xFFFFF;
         static constexpr __int20 unsigned min = 0;
     };
  ```
  
  However this has to be wrapped in an `#ifdef` as this is not compliant with ISO C++ forcing to disable `-pedantic` flag. 
  
  Do we consider this should be supported within the ETL library?

**Comment by jwellbelove** [comment]
Would you like to add this as a pull request?

**Comment by ReneCanadian** [comment]
Sure! I'll try to get something ready over the weekend :)

**Comment by jwellbelove** [comment]
Are you still planning to do a PR?

**Comment by ReneCanadian** [comment]
Ah yes sorry I'll try to have it this week, got a bit side  tracked
