### ISSUE TITLE
callback_timer: expose callback_timer_data::is_active() as icallback_timer public method

### ISSUE THREAD

**Issue by ilya-a1** [ETLCPP/etl#919]
Applications quite often need to check if a timer is active/running or is stopped.
It would be nice if icallback_timer can provide `bool is_active( etl::timer::id::type id_ )` method for checking if a timer is active.
Since callback_timer_data struct already implements is_active, icallback_timer's implementation could simply be the following
```
bool is_active(etl::timer::id::type id_) const
{
  if (has_active)
  {
    // Valid timer id?
    if (id_ != etl::timer::id::NO_TIMER)
    {
      const etl::callback_timer_data& timer = timer_array[id_];

      // Registered timer?
      if (timer.id != etl::timer::id::NO_TIMER)
      {
        return timer.is_active();
      }
    }
  }
  return false;
}
```

**Comment by jwellbelove** [comment]
Fixed 20.39.3
