### ISSUE TITLE
etl::unique_ptr reset 

### ISSUE THREAD

**Issue by fermentedfly** [ETLCPP/etl#921]
Hi,

I have some cases where I need to clear (`reset(nullptr)`) the content of a unique_ptr which may or may not be already cleared.
If it is already clear the assertion in `assert(p_ != p);` is triggered.
I was wondering if this should be the case since clearing what is already clear does seem fine to me.
I propose the assertion to be changed to `assert(p_ == nullptr || p_ != p);`, or maybe implement the overloaded `void reset( std::nullptr_t = nullptr )`
What do you think?

Regards,
Manuel

**Comment by jwellbelove** [comment]
Sounds reasonable

**Comment by fermentedfly** [comment]
Ok, do you want me to send you a PR?

**Comment by fermentedfly** [comment]
Thanks for implementing :)
