### ISSUE TITLE
ETL_USING_LEGACY_VARIANT Is always getting evaluated to 1

### ISSUE THREAD

**Issue by drewr95** [ETLCPP/etl#937]
It seems that ETL_USING_LEGACY_VARIANT is always getting evaluated to 1 for me.  I do not have ETL_USE_LEGACY_VARIANT defined, so the !ETL_USING_CPP11 must be getting evaluated to true.  I believe this is because these macros are defined before determining compiler versions.
 
![image](https://github.com/user-attachments/assets/bdf67fd0-c56f-45b6-af63-df31e214db51)

**Comment by drewr95** [comment]
Looks like VSCode is confirming this:
![image](https://github.com/user-attachments/assets/4d16b4dd-c36f-4d8c-a66c-fb9cf9f86fa0)


If we don't determine compiler version til line 153 (profiles/determine_compiler_version.h), how can ETL_USING_CPP11 be evaluated?

**Comment by drewr95** [comment]
Yeah, can confirm, if I move that macro below determining compiler version my builds work again

**Comment by jwellbelove** [comment]
Fixed 20.39.3
