### ISSUE TITLE
string insert vs assign

### ISSUE THREAD

**Issue by KammutierSpule** [ETLCPP/etl#960]
It looks insert does not "repair" the string. should it? or should put on documentation something about it?

**Comment by jwellbelove** [comment]
What do you mean by "repair"?

**Comment by KammutierSpule** [comment]
the test I did, I used insert and it didn't change (update) the size. 
Does it expects the repair() to be called?

**Comment by jwellbelove** [comment]
`repair()` is called by the user when a string has been moved by a low level C copy like `memcpy`. It just re-attaches the buffer to the internal pointer.

Can you give an example of an insert not updating the size?

**Comment by jwellbelove** [comment]
When you call `test.insert(0, buffer, buffer + 5)` you are calling this function
```
template <typename TIterator>
iterator insert(const_iterator position, TIterator first, TIterator last)
```
It is expecting the first parameter to be the iterator position where you want the string to be inserted. You are sending it a null iterator.

I assume you meant to call `test.insert(0, buffer, 5);`

It maybe worthwhile mw looking at trying to disable the insert if any of the iterators are integrals.
